### ISSUE TITLE
Estimate latent factor score with mixed mirt model

### ISSUE THREAD

**Issue by necollgree** [philchalmers/mirt#101]
Hi Phil,

I am trying to estimate the latent factor score using a mixed mirt model. The model looks like this:

mod <- mixedmirt(dat, covdat, model=1, lr.fixed=~t+status+tstatus, itemtype = 'graded')

It seems that I couldn't use fscores() anymore.

Also, I would like to compute the residuals for the latent variable regression model. I tried residuals() but it does not work either. Do you know how I can do that?

Thanks!

**Comment by philchalmers** [comment]
`residuals()` is not supported for these models (yet). And you want the `fixedef()` and `randef()` functions, not `fscores()`.
