### ISSUE TITLE
invalid SE type combinations

### ISSUE THREAD

**Issue by seonghobae** [philchalmers/mirt#104]
Hi, Phil.

I found invalid SE type combinations among SE type and method.

Can you check it?

Seongho

```R
# invalid cases
> testmod1 <- mirt(Science, 1, SE = T, SE.type = 'FMHRM', method = 'EM')
Iteration: 36, Log-Lik: -1608.870, Max-Change: 0.00010

Calculating information matrix...
> testmod1@Options$SE.type
[1] "FMHRM"

> testmod1 <- mirt(Science, 1, SE = T, SE.type = 'Oakes', method = 'MHRM')
Stage 3 = 103, LL = -1957.7, AR(6.00) = [0.30], gam = 0.0055, Max-Change = 0.0007

Calculating information matrix...

Calculating log-likelihood...
> testmod1@Options$SE.type
[1] "MHRM"

# valid case
> testmod1 <- mirt(Science, 1, SE = T, SE.type = 'crossprod', method = 'MHRM')
Error: SE.type not supported for MHRM method
```

**Comment by philchalmers** [comment]
That's not a valid case. If one is using the MHRM method then stochastic imputation is being performed. crossprod requires quadrature.

**Comment by philchalmers** [comment]
Oh I see what you mean. Yes, Oakes is not valid for MHRM. That should throw an error.

**Comment by seonghobae** [comment]
Also, FMHRM is not valid with EM. You may have to throw an error for invalid combinations.

MHRM + (QMC)EM
FMHRM + (QMC)EM

Richardson + MHRM
Oakes + MHRM
etc SE types + MHRM

**Comment by philchalmers** [comment]
The reason is this line:

```r
if((method == 'MHRM' || method == 'MIXED') && SE.type == 'Oakes') SE.type <- 'MHRM'
```

Basically, this just overwrites the default argument that is in `mirt(...)` when `method = 'MHRM'` is passed. The only clear fix here is that `SE.type` be changed to NULL by default. The new documentation makes it more clear that this change is occurring, because MHRM only supports a handful of `SE.type` methods due to its avoidance of numerical quadrature.

**Comment by philchalmers** [comment]
On Fri, Feb 24, 2017 at 11:54 AM, Seongho <notifications@github.com> wrote:

> Also, FMHRM is not valid with EM. You may have to throw an error for
> invalid combinations.
>
> MHRM + (QMC)EM
> FMHRM + (QMC)EM
>
> Richardson + MHRM
> Oakes + MHRM
> etc SE types + MHRM
>
Strange, this line should have stopped those:

if((method %in% c('MHRM', 'MIXED', 'SEM')) && !(SE.type %in% c('MHRM',
'FMHRM', 'none')))
        stop('SE.type not supported for stochastic method', call.=FALSE)

**Comment by seonghobae** [comment]
Okay, I've updated dev version on my machine, and I can see that.

```R
> testmod1 <- mirt(Science, 1, SE = T, SE.type = 'Richardson', method = 'MHRM')
Error: SE.type not supported for stochastic method
```

But I still do this.
```R
> testmod1 <- mirt(Science, 1, SE = T, SE.type = 'FMHRM', method = 'EM')
Iteration: 36, Log-Lik: -1608.870, Max-Change: 0.00010

Calculating information matrix...
> testmod1@Options$SE.type
[1] "FMHRM"
> testmod1 <- mirt(Science, 1, SE = T, SE.type = 'MHRM', method = 'EM')
Iteration: 36, Log-Lik: -1608.870, Max-Change: 0.00010

Calculating information matrix...
> testmod1@Options$SE.type
[1] "MHRM"
```

**Comment by seonghobae** [comment]
How about add this somewhere?

```R
if((method %in% c('EM', 'QMCEM')) && SE.type == 'MHRM') SE.type <- 'Oakes'
if((method %in% c('EM', 'QMCEM')) && SE.type == 'FMHRM') SE.type <- 'Oakes'
# if((method %in% c('BL')) && SE.type == 'MHRM') SE.type <- 'numerical'
# if((method %in% c('BL')) && SE.type == 'FMHRM') SE.type <- 'numerical'

if((method %in% c('EM', 'QMCEM', 'BL')) && !(SE.type %in% c('Richardson', 'forward',
                                                            'central', 'crossprod',
                                                            'Louis', 'sandwich',
                                                            'Oakes', 'complete',
                                                            'SEM', 'Fisher', 'numerical')))
  stop('SE.type not supported for non-stochastic method', call.=FALSE)
```

**Comment by philchalmers** [comment]
The MHRM and FMHRM are supported when method = 'EM'. So this is valid.

**Comment by seonghobae** [comment]
Okay, I got it. I didn't know the FMHRM and MHRM always valid for EM and QMCEM method. Thanks for your feedback.
