### ISSUE TITLE
ParObjects slots of multipleGroup models seem to be off

### ISSUE THREAD

**Issue by sumny** [philchalmers/mirt#114]
I know that one should not access S4 slots directly and rather use the extract.mirt function. Nevertheless, I wanted you to know that the ParObjects slot from a multipleGroup model probably does not look the way it should:

#mirt_1.24.4
library(mirt)
data <- expand.table(LSAT7)
group <- as.factor(rep(c(1, 2), dim(data)[1] / 2))
mod <- multipleGroup(data, 1, group)
mod@ParObjects

**Comment by philchalmers** [comment]
This is mainly because I don't include a lot of information in these objects by default. Though I suppose this could be a bit more graceful now that extraction of the internals is possible. I'll consider 'prettifying' these objects at some point.
