### ISSUE TITLE
Internals$Pl slot is empty (results in extract.mirt(mod, "exp_resp") returning NULL)

### ISSUE THREAD

**Issue by sumny** [philchalmers/mirt#115]
I just fetched the latest mirt version and noticed that the Internals$Pl slot currently returns NULL which results in extract.mirt(mod, "exp_resp") also returning NULL (this was not the case for I think mirt_1.23.x):

#mirt_1.24.4
library(mirt)
data <- expand.table(LSAT7)
mod <- mirt(data, 1)
mod@Internals$Pl

So I guess this is either a bug or did you move the expected probability slot?
Thanks in advance!

**Comment by philchalmers** [comment]
That looks to be a bug, it should be in there. When you change the method to 'MHRM' it shows up (also breaks `residuals(mod, type = 'exp')`. I'll add this in later, thanks for the report!

**Comment by sumny** [comment]
Hi again, thank you very much for the quick fix.
I think for multiple group models, there still is a small bug, as regardless of the number of group levels a list with only one slot is returned, e.g.:

#mirt_1.25.1
library(mirt)
data <- expand.table(LSAT7)
group <- as.factor(rep(c(1, 2), 500))
mod <- multipleGroup(data, 1, group)
mod@Internals$Pl

I would have expected one slot for each of the levels of the group variable, but maybe I miss something.
Thanks in advance!

**Comment by philchalmers** [comment]
Thanks, should be patched now.
