### ISSUE TITLE
g++: error: [[1]]: No such file or directory

### ISSUE THREAD

**Issue by rpietro** [philchalmers/mirt#124]
Hi Phil, I am trying to install mirt on a manjaro linux system, but keep getting the msg above. The issue is that I do have g++ installed in a standard path in this machine:

> ➜  ~ which g++
> /usr/bin/g++

I also have the latest version of RcppArmadillo, but also keep getting this warning::

g++  -I/usr/include/R/ -DNDEBUG  -I"/home/rpietro/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/rpietro/R/x86_64-pc-linux-gnu-library/3.4/RcppArmadillo/include" -D_FORTIFY_SOURCE=2   -fpic  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt  -c Estep.cpp -o Estep.o
In file included from /home/rpietro/R/x86_64-pc-linux-gnu-library/3.4/RcppArmadillo/include/armadillo:53:0,
                 from /home/rpietro/R/x86_64-pc-linux-gnu-library/3.4/RcppArmadillo/include/RcppArmadilloForward.h:46,
                 from /home/rpietro/R/x86_64-pc-linux-gnu-library/3.4/RcppArmadillo/include/RcppArmadillo.h:31,
                 from Misc.h:4,
                 from Estep.cpp:1:
/home/rpietro/R/x86_64-pc-linux-gnu-library/3.4/RcppArmadillo/include/armadillo_bits/compiler_setup.hpp:474:96: note: #pragma message: WARNING: use of OpenMP disabled; this compiler doesn't support OpenMP 3.0+
   #pragma message ("WARNING: use of OpenMP disabled; this compiler doesn't support OpenMP 3.0+")

Any thoughts on what the problem might be? 

thanks

**Comment by philchalmers** [comment]
I don't see an error in this output (on the contrary, it looks like it compiled fine). The pragma output message is something new from RcppArmadillo that I've noticed, and I haven't figured out how to suppress it yet. Nevertheless, if you are seeing these warnings you're probably installing the source files correctly.

**Comment by rpietro** [comment]
@philchalmers , thanks for getting back to me so quickly. Unfortunately, it was not installing. But based on your msg I checked a few other warnings related to the packages called from my Rprofile. I still don't understand exactly what was happening, but when I bypassed my Rprofile while opening R the installation went smoothly. Thanks again
