### ISSUE TITLE
Problem with multipleGroup

### ISSUE THREAD

**Issue by fiuzamoura** [philchalmers/mirt#125]
Hello Phil! How are you?

I am new to R and MIRT and I`m having an issue....

I`m trying to equate two groups of examinees, with two forms. The non-reference group answered 6 items which where  previously presented to the reference group.

Here is my problem:

 "What I want to do:

I want to perform a Fixed Parameter Model between two groups, where the first group is the reference

Datasets (forms):

One dataset with right Vs wrong (dichotomous) answers from the reference group, in which every item has a unique name.

A second dataset with right Vs wrong (dichotomous) answers, from the group I want to generate estimates. Again, each item has a unique name. In this second data-set there are 6 common itens from the first data-set (correctly named/identified)

charging datasets:

group_one <- 
  read.csv2("first_group.csv")

group_two <- 
  read.csv2("second_group.csv")

#----estimating the item coeficients of the reference group----#
defining the model
first_model <-
  mirt.model('F1 = 1-15
                      PRIOR = (1-15, a1, lnorm, 0, 0.5), (1-15, g, norm, -1.386, 0.5)')

using mirt to estimate
first_model_estimates <- mirt(group_one, first_model, itemtype = "3PL", SE = TRUE,
                              quadpts = 40, TOL = 0.001)

saving item coeficients generated by the mirt model
first_model_coefs <- (coefs=coef(first_model_estimates, IRTpars = TRUE, simplify = TRUE)) %>%
  as.data.frame()

transforming coefs into vectors
a1 <- first_model_coefs$items.a %>%
  as.vector()

b <- first_model_coefs$items.b %>%
  as.vector()

g <- first_model_coefs$items.g %>%
  as.vector()

#----- Starting the multigroup model-------#

binding datasets the two groups together
multi_group_dataset <-
  bind_rows(group_one, group_two)

Creating groups ID
groups_id <- c(rep("g_1",nrow(group_one)),rep("g_2",nrow(group_two)))

identifying the common fixed parameters itens
names_first <- colnames(group_one)
names_second <- colnames(group_two)

fixed_common_itens <-
  names_first %>%
  intersect(names_second)

writing the multigroup model
second_model <-
  mirt.model('F1 = 1-31
             FIXED = (1-15, a1), (1-15, d), (1-15, g),
             PRIOR = (16-31, a1, lnorm, 0, 0.5), (16-31, g, norm, -1.386, 0.5)')

Creating an example data.frame to input the fixed parameters later
parameters <- multipleGroup(multi_group_dataset, model=second_model, group = groups_id, 
                            itemtype = '3PL',
                            SE=TRUE, quadpts=40,
                            TOL = 0.001,
                            pars = 'values',
                            invariance = c(fixed_common_itens, 'free_means', 'free_var'))

Selecting the itens to be fixed, which the true parameters a1 will be writen in the "parameters" dataset
(pick <- filter(parameters, name == "a1" & item %in% paste0("ENADE",9:35))$parnum)

replacing the a1 parameters in the dataset
parameters$value[pick] <- a1

Selecting the itens to be fixed, which the true parameters d will be writen in the "parameters" dataset
(pick <- filter(parameters, name == "d" & item %in% paste0("ENADE",9:35))$parnum)

replacing the a1 parameters in the dataset
parameters$value[pick] <- b

Selecting the itens to be fixed, which the true parameters g will be writen in the "parameters" dataset
(pick <- filter(parameters, name == "g" & item %in% paste0("ENADE",9:35))$parnum)

replacing the a1 parameters in the dataset
parameters$value[pick] <- g

Creating the third model
third_model <-
  mirt.model('F1 = 1-31
             FIXED = (1-15, a1), (1-15, d), (1-15, g),
             PRIOR = (16-31, a1, lnorm, 0, 0.5), (16-31, g, norm, -1.386, 0.5)')

Trying to estimate the parameters with fixed itens
parameters2 <- multipleGroup(multi_group_dataset, third_model, group = groups_id,
                             itemtype = '3PL',
                             SE=TRUE, quadpts=40,
                             TOL = 0.001,
                             pars = parameters,
                             invariance = c(fixed_common_itens, 'free_means', 'free_var'))

Here is the point things get annoying. After executing the multiplegroup above, R writes the following error:

Error: jj > 0 is not TRUE

I have searched everywhere to find a solution for this problem, but didn`t succed.
Could you help me with this task?
Thanks in advance ;)

Here is the link to the code and to the datasets:
https://kroton-my.sharepoint.com/personal/flavio_fiuza_kroton_com_br/_layouts/15/guestaccess.aspx?folderid=1232b00bf542d45ac890f5a7b0a6211ad&authkey=AfG8rzqcbXGJOgQTaD9QbCk

**Comment by philchalmers** [comment]
This error is cryptic (I've patched that part), but it does stop you from doing something a bit odd. If you are just fixing all your parameters in the anchor items as fixed and known then there's no point in running `multipleGroup()`, and instead you could just set up each group with `mirt()`. The `invariance` input is what is causing the error, because you are telling mirt to constrain the anchor item parameters to be equal (assuming they were estimated, when in fact they were fixed...so this equality is meaningless).
