### ISSUE TITLE
Davidian Curve IRT implementation in mirt?

### ISSUE THREAD

**Issue by oguzhanogreden** [philchalmers/mirt#130]
Hi,

You may be familiar with Davidian Curve IRT (DC-IRT) [1]. These methods have been receiving some attention in my field, also see [2].

I am considering following up on these as part of my research project. So I've been taking a look at the `mirt` codebase to see if I could provide an accessible implementation of DC-IRT via `mirt`. As far as I can tell, implementing this amounts to following changes:

1. Modifying `Mstep.LL()`, specifically
    1. `LogLikMstep()` to add the extra term in Equation 14 in [1].
    1. And change the conditional which assumes that ```any(pars[[g]][[J+1L]]@est) == T``` implies ```Mstep.LL.group()``` is needed.
2. Modifying `Mstep.grad()` _(I'm still reading this bit and the relevant C++ function to identify what needs modification)_

I noticed 1.ii and decided to bring this issue to here. Since, that piece likely has some reflections elsewhere and requires more familiarity with the code base than I could gather in half a day. I'm also curious if @philchalmers would be willing to consider such changes, to provide DC-IRT to `mirt` users.

Best.

---
[1] Woods, C. M., & Lin, N. (2009). Item response theory with estimation of the latent density using Davidian curves. Applied Psychological Measurement, 33(2), 102-117.
[2] Reise, S. P., Rodriguez, A., Spritzer, K. L., & Hays, R. D. (2017). Alternative Approaches to Addressing Non-Normal Distributions in the Application of IRT Models to Personality Measures. Journal of Personality Assessment, 1-12.

**Comment by philchalmers** [comment]
I'm certainly not opposed to adding such a feature to `mirt`, though the time that I have to code new features is somewhat limited now that I've started a new position (sadly, the days of coding as a grad-student has come to an end). 

That said, I'm not opposed to helping others work on different forks of `mirt` to add new features; this seems to be the trend that people are taking with the package. If you can help provide the general setup, and certainly the required log-likelihood/derivative terms (even if they are written purely in R code), then I'd be happy to help add such a feature to the master branch.

**Comment by oguzhanogreden** [comment]
I'll try to tackle this then and let you know when there's enough improvement to consider a merge.

**Comment by oguzhanogreden** [comment]
Hi,

I would like to check an issue about EM algorithm with you.

I now have a modified version of `mirt()` which uses Davidian curves to estimate latent density. This is an integration of a couple utility functions implemented in [`davidRian` package](https://github.com/oguzhanogreden/davidRian). I verified that these can recover the form of a unidimensional density in conditions similar to EM context (e.g. N = 61).

The goal with integration to mirt is to perform EM like this:

>DC-IRT is a modification of classic EM MML IRT. In every E-step, the current estimate of g(θ) is used in place of the normal distribution. In every M-step, after all of the item parameters are re-estimated, there is one more Newton-Raphson maximization to estimate Davidian curve parameters. The Davidian curve likelihood is Lg = [...], where q = 1, 2, …, Q counts quadrature points, N(θq) is the expected number (fraction) of people at each quadrature point.  [1]

I identified the relevant modifications as follows. For M step: [adding another optimization step](https://github.com/oguzhanogreden/mirt/blob/dcirt/R/EMstep.utils.R#L70), defining the [likelihood](https://github.com/oguzhanogreden/mirt/blob/dcirt/R/EMstep.utils.R#L228) and [gradient](https://github.com/oguzhanogreden/mirt/blob/dcirt/R/EMstep.utils.R#L266) functions for this. For E step is [adding Davidian curve density to `updatePrior()`](https://github.com/oguzhanogreden/mirt/blob/dcirt/R/utils.R#L385)

I perform tests by estimating models and plotting the density specified by Davidian curve parameters. Using this criteria, it doesn't seem to work. Specifically, it becomes skewed in the correct direction, but not close enough to how the latent density looks.

When I inspect the iterations, I observe that parameters of the Davidian density move very little from the normal density. I suspect this is about N(θq), since I understand that this is a term that functions as a weight to the relevant LL in the M step, also as described in the above mentioned source. I am using `relevantGroupPars@rr / sum(relevantGroupPars@rr)` (also tried `relevantGroupPars@rr`) to get N(θq) as described above. I decided this seeing its use [here](https://github.com/philchalmers/mirt/blob/master/R/EMstep.utils.R#L205).

Does this make sense to you? Or does it make you say "I would check/try this?"

---

[1]: Chapter 4 of The Handbook of Item Response Theory Modeling (Reise and Revicki, 2015), page 76

**Comment by seonghobae** [comment]
How about add “DCEM” as a new method? Standard MML/EM calibration is essential. Moreover, the sixty-one quadrature points are not relevant here even new process can recover the parameters in the context of UIRT. If a new procedure cannot work well in multidimensional models, that's not the proper way.

**Comment by philchalmers** [comment]
@seonghobae to the best of my knowledge DC-IRT models do not have a good MIRT analogue, so the fact that it doesn't generalise well is fine (similar issues occur of empirical histograms, which mirt currently supports). 

@oguzhanogreden can you provide a reproducible example? I'd be happy to play around with this in your forked version, though I think discussing the issue here on the master branch is not overly useful at this time. 

Please open an issue on your public version of `mirt`, with some code to demonstrate this issue (ideally, with some previously worked example data and output with which we can compare). Cheers.

**Comment by seonghobae** [comment]
Okay, How about adding the DC-IRT as an argument a kind of UIRT? Empirical Histogram is good (and similar) example of implementation of UIRT method. It's just idea for this issue.

**Comment by philchalmers** [comment]
If/when this technique gets merged in I'll likely do something like that, though perhaps instead of adding so many new logical argument flags to mirt (e.g., `mirt(..., empiricalhist = TRUE)`) there may just be a new `trait.type = 'Gaussian'` default which could be changed to `trait.type = 'empiricalhist'` or `trait.type = 'DC'`, so something to that extent. It will be documented in the NEWS file of course if I decide to go that route since it will break some previous code.

**Comment by oguzhanogreden** [comment]
I created an issue in my fork as requested. I will keep it up to date if I have any progress on this.

**Comment by seonghobae** [comment]
Interesting. I saw the http://www.oguzhanogreden.com/mirt/ what delivers demonstration what @oguzhanogreden want to implement. I wondering DC-IRT uses the Ramsay method. As the default, mirt::mirt() uses the Ramsay as the accelerator during calibrate the model. However, It seems to get rid of Ramsay method in the demonstration. If @oguzhanogreden want to implement DC-IRT as an alternative method of Ramsay method, much better adding technical flags or ```accelerate = 'Davidian'```.

**Comment by philchalmers** [comment]
@seonghobae Ramsay acceleration is a very different thing, based on his 1975 paper on implicit equations. 

@oguzhanogreden thank you, I'll take a look at your repo and this issue when I get a chance over the next few days. Cheers.

**Comment by seonghobae** [comment]
@philchalmers Thanks for commenting! I confused @oguzhanogreden noted about RC-IRT. I'll take a look more articles. Thanks again!
