### ISSUE TITLE
reloadPars() removes names of par vector

### ISSUE THREAD

**Issue by oguzhanogreden** [philchalmers/mirt#133]
Hello,

I'm closing up on #130 and I noticed an unexpected behavior with `reloadPars(longpars, pars, ngroups, J)`. I will first describe the problem in isolation, which is enough for a simple fix. I then give background, since someone may be able point a better solution to my actual problem.

# Problem

The object returned from `reloadPars(longpars, pars, ngroups, J)` removes the names of parameter vectors.

This is not visible at the moment because names of this vector are not used, as far as I can see, except for result printing purposes. (I didn't track down where they are recovered, since I don't expect it'll solve my problem.)

## How to observe?

This can observed by creating a breakpoint in reloadPars() and observing the names before and after source call.

Try for instance `names(pars[[1]][[J+1L]]@par)`. You will be able to read the names before the call to C++ code but not after.

## Why is it unexpected? 

This is unexpected since the the object returned from `reloadPars()` is very often assigned back to `pars` argument. Also, when extending `mirt` functionality, it is reasonable that I expect to be able to access and read a slot of a certain class in a uniform manner throughout the program.

# Background

#130 requires that we estimate extra group parameters for DC density. This pointed my attention to `ExtractGroupPars()` and `LoadGroupPars()`. Changes in `LoadGroupPars()` are straight-forward, I'll skip them for now.

However, `ExtractGroupPars(x)` is not flexible enough. Currently, it expects `x@par` to be of a certain format. To be precise, the first `nfact` elements are expected to be means and the rest covariances, see [`ExtractGroupPars()`](https://github.com/philchalmers/mirt/blob/18db22c3cf4a7ba7436905bba2bc1829d28d275f/R/utils.R#L291).

I am adding DC density parameters to this vector. This makes names relevant, since I can then use the names to extract the parameters. The number of parameters are user defined, independent of other parameters.

Best,
Oguzhan

**Comment by philchalmers** [comment]
Thanks. I've known about this behavior as well. The names are also stored in the `@est` slot too, which is where I go to extract the respective names rather than from the constantly changing parameter estimates. Does that help solve your problem?

**Comment by philchalmers** [comment]
I'm going to close this for now as it isn't an issue with the current master branch. If you still are having issues please feel free to comment.
