### ISSUE TITLE
dentype in mdirt

### ISSUE THREAD

**Issue by seonghobae** [philchalmers/mirt#141]
Hi,

I found the dentype argument not working properly, so that I report this.

Best,
Seongho

```R
> mirt::mdirt(mirt::Science, 1, dentype = 'EH')
Error in makeopts(GenRandomPars = GenRandomPars, hasCustomGroup = !is.null(customGroup),  : 
  formal argument "dentype" matched by multiple actual arguments
```

**Comment by philchalmers** [comment]
The value for dentype is actually fixed at 'discrete' for this function, which is why this fails. This probably should be documented better.

**Comment by seonghobae** [comment]
Yeah, I agree. Previously, that argument could be passed.

**Comment by philchalmers** [comment]
Sure, but `empiricalhist` would have been ignored by this function. Another good reason why this `dentype` argument was formed (less ambiguity).
