### ISSUE TITLE
coef(., IRTpars = T) produces: Error in dimnames(x) <- dn : length of 'dimnames' [2] not equal to array extent

### ISSUE THREAD

**Issue by Daniel-Gundersen** [philchalmers/mirt#146]
A 16 item unidimensional model with a mix of 2PL and 2PLNRM items produces the following error I call 
`coef(fit, simplify = T, IRTpars = T)`:

> Error in dimnames(x) <- dn : 
>   length of 'dimnames' [2] not equal to array extent
> In addition: Warning message:
> In matrix(c(object@ParObjects$pars[[i]]@par, object@ParObjects$pars[[i]]@par -  :
>   data length [8] is not a sub-multiple or multiple of the number of rows [3]

If I ask for slope - intercept rather than IRT parameters it prints the table with no error.  If I fit the model with SE = FALSE it will print either slope-intercept or IRT parameters without error.  

Here is a reproducible example:

```
library(mirt)

set.seed(4321)
a <- matrix(rep(1, 16))
d <- runif(16, -2.5, 2.5)
d0 <- c(rep(NA, 7), rep(0, 9))

d1 <- c(rep(NA, 7), runif(9, -2, 2))

intercepts <- matrix(c(d, d0, d1), ncol = 3)
            
ak <- rep(NA, 16)

ak0 <- c(rep(NA, 7), rep(0, 9))
         
ak1 <- c(rep(NA, 7), rep(1, 9))

nominal <- matrix(c(ak, ak0, ak1), ncol = 3)

items <- c(rep("2PL", 7), rep("2PLNRM", 9))

df <- simdata(a, intercepts, 591, itemtype = c(rep("2PL", 7), rep("2PLNRM", 9)), 
              nominal = nominal)
              
mod.se <- mirt(df, 1, 
             itemtype = c(rep("2PL", 7), rep("2PLNRM", 9)), 
             key = c(rep(NA, 7), rep(0, 9)),
             SE = T)

coef(mod.se, simplify = T, IRTpars = T)
```

> Error in dimnames(x) <- dn : 
>   length of 'dimnames' [2] not equal to array extent
> In addition: Warning message:
> In matrix(c(object@ParObjects$pars[[i]]@par, object@ParObjects$pars[[i]]@par -  :
>   data length [8] is not a sub-multiple or multiple of the number of rows [3]

```
mod.no.se <- mirt(df, 1, 
               itemtype = c(rep("2PL", 7), rep("2PLNRM", 9)), 
               key = c(rep(NA, 7), rep(0, 9)),
               SE = F)
coef(mod.no.se, simplify = T, IRTpars = T)
```

> $`items`
>              a      b    g   u     a1     a2     c1     c2
> Item_1  -0.993 -2.281    0   1     NA     NA     NA     NA
> Item_2  -0.867 -1.838    0   1     NA     NA     NA     NA
> Item_3  -1.351  0.336    0   1     NA     NA     NA     NA
> Item_4  -0.966  0.849    0   1     NA     NA     NA     NA
> Item_5  -1.132 -0.212    0   1     NA     NA     NA     NA
> Item_6  -1.121 -1.960    0   1     NA     NA     NA     NA
> Item_7  -0.962 -0.035    0   1     NA     NA     NA     NA
> Item_8   1.121 -0.008 -999 999 -0.148  0.148  0.624 -0.624
> Item_9   1.813 -0.097 -999 999 -0.132  0.132 -0.327  0.327
> Item_10  1.146  1.766 -999 999 -0.236  0.236  1.107 -1.107
> Item_11  2.481  1.374 -999 999 -0.405  0.405  0.705 -0.705
> Item_12  1.687  1.528 -999 999 -0.159  0.159  0.578 -0.578
> Item_13  1.272  0.918 -999 999  0.046 -0.046  1.628 -1.628
> Item_14  1.178  1.650 -999 999  0.000  0.000  1.503 -1.503
> Item_15  1.006 -0.288 -999 999 -0.086  0.086  0.746 -0.746
> Item_16  1.014  1.303 -999 999 -0.319  0.319  0.097 -0.097
> 
> $means
> F1 
>  0 
> 
> $cov
>    F1
> F1  1

Here is my session info:

`sessionInfo()`
> R version 3.5.1 (2018-07-02)
> Platform: i386-w64-mingw32/i386 (32-bit)
> Running under: Windows 7 (build 7601) Service Pack 1
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
> [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
> [5] LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] stats4    stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] tableone_0.9.3  mirt_1.28       bindrcpp_0.2.2  readxl_1.1.0    forcats_0.3.0   stringr_1.3.1  
>  [7] dplyr_0.7.6     purrr_0.2.5     readr_1.1.1     tidyr_0.8.1     tibble_1.4.2    tidyverse_1.2.1
> [13] Hmisc_4.1-1     ggplot2_3.0.0   Formula_1.2-3   survival_2.42-3 lattice_0.20-35
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_0.12.17          bindr_0.1.1           knitr_1.20            xml2_1.2.0           
>  [5] magrittr_1.5          cluster_2.0.7-1       MASS_7.3-50           splines_3.5.1        
>  [9] hms_0.4.2             mnormt_1.5-5          rvest_0.3.2           tidyselect_0.2.4     
> [13] colorspace_1.3-2      Deriv_3.8.5           R6_2.2.2              rlang_0.2.1          
> [17] parallel_3.5.1        broom_0.4.5           vegan_2.5-2           e1071_1.6-8          
> [21] latticeExtra_0.6-28   modelr_0.1.2          withr_2.1.2           class_7.3-14         
> [25] htmltools_0.3.6       assertthat_0.2.0      digest_0.6.15         permute_0.9-4        
> [29] Matrix_1.2-14         acepack_1.4.1         haven_1.1.2           compiler_3.5.1       
> [33] cellranger_1.1.0      pillar_1.2.3          scales_0.5.0          backports_1.1.2      
> [37] lubridate_1.7.4       jsonlite_1.5          pkgconfig_2.0.1       survey_3.33-2        
> [41] rstudioapi_0.7        munsell_0.5.0         highr_0.7             dcurver_0.9.1        
> [45] httr_1.3.1            plyr_1.8.4            tools_3.5.1           grid_3.5.1           
> [49] nnet_7.3-12           nlme_3.1-137          htmlTable_1.12        data.table_1.11.4    
> [53] gtable_0.2.0          checkmate_1.8.5       mgcv_1.8-24           utf8_1.1.4           
> [57] psych_1.8.4           cli_1.0.0             lazyeval_0.2.1        yaml_2.1.19          
> [61] GPArotation_2014.11-1 crayon_1.3.4          gridExtra_2.3         reshape2_1.4.3       
> [65] RColorBrewer_1.1-2    htmlwidgets_1.2       base64enc_0.1-3       labelled_1.1.0       
> [69] rpart_4.1-13          glue_1.2.0            stringi_1.1.7         foreign_0.8-70       
> [73] zoo_1.8-2

**Comment by philchalmers** [comment]
This should be fixed now on the dev version. Thanks for the report!
