### ISSUE TITLE
mirt output can be huge on disk after save()

### ISSUE THREAD

**Issue by hplieninger** [philchalmers/mirt#147]
I noticed that file sizes can be huge when `save()`ing a mirt object to disk. This seems to be related to the estimation method (i.e., `method = "QMCEM"`). More precisely, the objects `den` and `safe_den` in `ParObjects`'s slot `GroupPars` are functions that can take up a huge amount of space. Probably, because their environments are also saved (see, e.g., https://stackoverflow.com/a/49603965/2563804).

I don't know enough about these functions and environments in general, so I can't judge whether the described behavior is necessary or can be changed. But I wanted to ask, because this can make a huge difference in file sizes; in the example below, it's 1400 Kb vs. 45 Kb just because of storing or not a seemingly small function.

``` r
library(mirt)
#> Loading required package: stats4
#> Loading required package: lattice

data <- expand.table(LSAT7)

cmodel <- mirt.model("F1 = 1-5")

cmod <- mirt(data, cmodel,
             method = "QMCEM",
             quadpts = 5000)

# Object size when saving mirt output -------------------------------------

pryr::object_size(cmod)
#> 992 kB
format(object.size(cmod), units = "Kb")
#> [1] "318.2 Kb"

file1 <- tempfile(fileext = "RData")
file2 <- tempfile(fileext = "RData")

save(cmod, file = file1)

tmp1 <- file.info(file1)$size
class(tmp1) <- "object_size"
print(tmp1, units = "Kb")
#> 1405.1 Kb


# Object size when saving modified mirt output ----------------------------

cmod2 <- cmod

cmod2@ParObjects$pars[[6]]@den <- function () NULL
cmod2@ParObjects$pars[[6]]@safe_den <- function () NULL

pryr::object_size(cmod2)
#> 285 kB
format(object.size(cmod2), units = "Kb")
#> [1] "283.3 Kb"

save(cmod2, file = file2)

tmp2 <- file.info(file2)$size
class(tmp2) <- "object_size"
print(tmp2, units = "Kb")
#> 45 Kb
```

Created on 2018-08-20 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by philchalmers** [comment]
"huge" is overstatement here, but I see your point about the function enviroment information being needless. Are there any other instances like this in the returned object?

**Comment by philchalmers** [comment]
I've lessened this problem a little, but I wouldn't consider it "solved" just yet. Moreover, I'm unsure why R has this type of saving workspace behaviour with respect to functions, and simply setting the enviroment to an empty one doesn't solve the problem either (I tried `enviroment(obj@den) <- new.env()`, which changed the size, but not perfectly). I'll leave this open for now in case I discover a more effective approach.

**Comment by hplieninger** [comment]
Thanks for your time and effort.

After seeing your comment, I had another idea. Maybe `environment(obj@den) <- new.env(parent = emptyenv())` will solve the problem. Otherwise one may "accidentally inherit objects from somewhere else" as Hadley states in [Advanced R](http://adv-r.had.co.nz/Environments.html#explicit-envs). This worked with a mock example I tried, but i have not tested it with `mirt()`.

I agree that "huge" was overstated for the example above. But the problem increases with increasing quadpts, and when running multiple models or even a simulation study.

**Comment by philchalmers** [comment]
Thank you for the suggestion, I'll check it out. I suspect a similar problem occurs in the `createItem()` portion of the package, so I'll check to see if there are other functional definition areas where this problem arises. 

I agree about the problem of running multiple models with this memory bloating, especially because R is rather memory hungry at times, but for simulation studies I would probably recommend extracting the estimates you need rather than saving full estimation object that necessarily contain more information than you need. At least, that's the philosophy I impose in my `SimDesign` package.

**Comment by philchalmers** [comment]
I tried your `new.env(parent = emptyenv())` recommendation, but did not see any detectable difference between the current improvement. Looking closer though, this problem may have been solved as the increase in object size no longer blows-up with larger quad points, though a slight increase is still present. I'm going to mark this as solved for now, because the size difference between the following isn't so bad anymore:

```{r}
library(mirt)

data <- expand.table(LSAT7)
cmodel <- mirt.model("F1 = 1-5")
cmod100 <- mirt(data, cmodel,
             method = "QMCEM",
             quadpts = 100)
cmod1000 <- mirt(data, cmodel,
                method = "QMCEM",
                quadpts = 1000)
cmod50000 <- mirt(data, cmodel,
                method = "QMCEM",
                quadpts = 50000)

format(object.size(cmod100), units = "Kb")
format(object.size(cmod1000), units = "Kb")
format(object.size(cmod50000), units = "Kb")

# [1] "228.9 Kb"
# [1] "243 Kb"
# [1] "1008.6 Kb"
```

**Comment by hplieninger** [comment]
Yeah, that suggestion was not meant to replace your commit 2b5289236a20e90212c7a89d7adbb3c0cf90dd7b. Rather, I was trying to understand why `new.env()` did not work. I guess, the effect on the `save()`d file size is the same whether the function's environment is the package environment (as you did) or a `new.env(parent = emptyenv())`. But your solution seems much cleaner to me, and I am more than happy with the current version.

Once again, thanks for your time and effort, not only with respect to this issue but also with respect to both mirt and SimDesign.
