### ISSUE TITLE
M2() fails for gpcms

### ISSUE THREAD

**Issue by sumny** [philchalmers/mirt#149]
Reproducible via:

```R
library(mirt) #mirt_1.29.5

#M2() not working for gpcm
gpcm <- mirt(SAT12, 1, "gpcm")
M2(gpcm)
```
with M2(gpcm) yielding:
Error in dp[, nfact + ncat + j] <- e[j] * P[, j] - e[j] * P[, j]^2 - as.numeric(e[-j] %*%  : 
  number of items to replace is not a multiple of replacement length

**Comment by philchalmers** [comment]
Thanks. Related to R's annoying `drop = TRUE` default in matrix operations.
