### ISSUE TITLE
areainfo gives error message with MultipleGroupClass

### ISSUE THREAD

**Issue by TomBentonCA** [philchalmers/mirt#150]
#for example
data <- expand.table(LSAT7)
mg1=multipleGroup(data, 1,group=rep(c("A","B"),each=500)
	,invariance=c("free_means","free_var","slopes","intercepts"),TOL=0.01)
areainfo(mg1,c(-1,2),which.items = 1)

#this could be easily fixed by amending the function to have a "group" input and allowing this to
#input into the testinfo part.
#the new function would be as below
areainfo=function (x, theta_lim, which.items = 1:extract.mirt(x, "nitems"), group=group,...) {
    f <- function(theta, x, which.items) testinfo(x = x, Theta = matrix(theta), 
        which.items = which.items,group=group)
    if (missing(x)) 
        missingMsg("x")
    if (missing(theta_lim)) 
        missingMsg("theta_lim")
    stopifnot(length(theta_lim) == 2L)
    stopifnot(extract.mirt(x, "nfact") == 1L)
    nitems <- ifelse(is.null(which.items), extract.mirt(x, "nitems"), 
        length(which.items))
    ii <- integrate(f, lower = theta_lim[1L], upper = theta_lim[2L], 
        x = x, which.items = which.items, ...)
    iT <- integrate(f, lower = -10, upper = 10, x = x, which.items = which.items, 
        ...)
    ret <- data.frame(LowerBound = min(theta_lim), UpperBound = max(theta_lim), 
        Info = ii$value, TotalInfo = iT$value, Proportion = ii$value/iT$value, 
        nitems = nitems)
    rownames(ret) <- ""
    ret
}

**Comment by philchalmers** [comment]
Thanks. I imagine this type of functional adjustment could be made to a number of `mirt`'s functions. When I get a chance I'll look into adding your suggestion to `areainfo()` as well as other related secondary functions.
