### ISSUE TITLE
mod2values fails for MixtureClass

### ISSUE THREAD

**Issue by TomBentonCA** [philchalmers/mirt#152]
For example,

mg1=multipleGroup(Science,1,dentype="mixture-2")

mod2values(mg1)

gives an error

I think this can easily be fixed by changing the first line of the mod2values function so it includes "MixtureClass", that is,...

    if (is(x, "MultipleGroupClass") || is(x, "DiscreteClass")||is(x, "MixtureClass")) {

**Comment by philchalmers** [comment]
Thanks. This was also broken internally if the starting values object were to be passed to `multipleGroup(..., pars=)`. Both are patched now. Thanks for the report!
