### ISSUE TITLE
log likelihood doesn't update for last iteration

### ISSUE THREAD

**Issue by stenhaug** [philchalmers/mirt#153]
I believe that if the fit stops because NCYCLES has been hit, then the fit statistics like log likelihood are not calculated a final time.

For example, with NCYCLES = 2

- Fit cycle 1
- Calculate log lik for cycle 1
- Fit cycle 2 
- STOP

So the output of fit is from cycle 1 not after updating parameters in cycle 2

**Comment by philchalmers** [comment]
Practically speaking this should make no difference for models that have converged, but you're right this last log-likelihood should be computed based on the final parameter set. I'll push this change shortly.
