### ISSUE TITLE
Error with "residuals" function to get LD matrix

### ISSUE THREAD

**Issue by kangx373** [philchalmers/mirt#154]
I'm keep getting this error message when I'm trying to run the "residuals" function to get the LD output. I deleted all the cases with missing values using "na.omit" function so I have no idea why I'm getting this error. Here is the error message:

> LD_uniGR = residuals(uniGR, type="LD")
Error in if (s == 0) s <- 1 : missing value where TRUE/FALSE needed
In addition: Warning message:
In x * mapply(mat.lr, r = r.x, c = c.x, MoreArgs = list(r.x = r.x,  :
  NAs produced by integer overflow

What is the issue here and how can I fix it?

Thank you!

**Comment by philchalmers** [comment]
Looks like some type of bug. Can you provide a reproducible example?

**Comment by kangx373** [comment]
I attached the data that has 36 columns and 270966 rows (after removing cases with missing values). Here is the code I used:


[data.txt](https://github.com/philchalmers/mirt/files/3025738/data.txt)

```
my.data = read.csv("data.csv", header = TRUE, sep=",")
irt.data = na.omit(my.data)
uniGR<-mirt(irt.data, 1, SE = TRUE)
LD_uniGR = residuals(uniGR, type="LD")
```

I coudln't attach the original .csv file so transformed it into .txt (tab delimited) and attaced here.
Thank you.

**Comment by philchalmers** [comment]
Thanks, this should be patched now.
