### ISSUE TITLE
suggestion for make more detail user manual

### ISSUE THREAD

**Issue by gitbobo** [philchalmers/mirt#155]
In the `line 26` of `Example_01.R`,you mentioned `#in slope-intercept form, use b = -d/a to obtain traditional metric`.  

Then, where to use ` b = -d/a`?  

Thanks for your great mirt! I want it be a all-in-one IRT package.

**Comment by philchalmers** [comment]
Pull requests are welcome if you have specific contributions to make. Otherwise, it would be extremely difficult to include everything IRT related in the package. Most of this information can be found in the references provided in the package or have been answered on the `mirt-package` forum.
