### ISSUE TITLE
fscores colnames for method="EAPsum"

### ISSUE THREAD

**Issue by TomBentonCA** [philchalmers/mirt#171]
Have noticed that if method="EAPsum" is used within fscores then the standard error of theta has the name "SE.Theta". All of the other methods produde standrd errors that are prefixed with "SE_". This causes issues when using the "empirical_rxx" function as it start by looking for a column with "SE_" in it.

Probably easiest to fix this by amending the "empirical_rxx" function so the line that currently says

is_SE <- grepl("SE_", nms)

is changed to

is_SE <- (grepl("SE_", nms)|grepl("SE.Theta", nms))

**Comment by philchalmers** [comment]
Thanks. I decided to change the `'EAPsum'` method where the `SE`-type columns use the `SE_` convention. Let me know if this fixes your issue.

**Comment by TomBentonCA** [comment]
Thanks. That will work fine.
