### ISSUE TITLE
Strange results: coefficients of an item do not correspond to its itemplot...

### ISSUE THREAD

**Issue by alinaoshina** [philchalmers/mirt#173]
Hi,
I fitted a 3PL model to a dichotomous 27-item spatial reasoning test data. the M2 function shows nice fit, even though model fit terminated after 500 iterations... 
I noticed an item with strange parameters: a1 = 5.74216; d = -2.247903; g = 0.3263463. But when I created an itemplot of this item, it showed a very steep curve indeed, but the steepest point somewhere around theta = 0.2, not -2.25 at all... I checked several times that I do not mix that item up with any other item... this question is also not supposed to be an easy question....
<img width="935" alt="item trace lines" src="https://user-images.githubusercontent.com/38853122/72477033-5b834200-37f7-11ea-806b-5c7f4f3c8e69.PNG"> this is item SRT_Q19...
What am I doing wrong? the graph is not consistent with the coefs.... 
Thanks and sorry for the bother...

**Comment by philchalmers** [comment]
`d` is an intercept parameter, not a difficulty parameter. It represents the logit location when $\theta = 0$ rather than the point at which $P(y | \theta)$ inflects. If you want the classical parameterizations use `coef(mod, IRTpars = TRUE)`. HTH.

**Comment by alinaoshina** [comment]
Thank you so much, Phil.
That helps a lot.
All the best,
Alina
