### ISSUE TITLE
MIRT survey-weights option breaks M2 calculations

### ISSUE THREAD

**Issue by dcoven** [philchalmers/mirt#174]
The M2() limited information statistics do not properly account for survey weights in the model. The following calculates a model from an expanded table and from using weights, yet M2 is wildly different for the two methods.

LSAT6_Expanded <- expand.table(LSAT6)
dim(LSAT6_Expanded)
mod_Expanded <- mirt(LSAT6_Expanded, 1, "Rasch")
M2(mod_Expanded )

mod_Survey<- mirt(LSAT6[,1:5], 1, "Rasch", survey.weights =LSAT6[,6] )
sum(LSAT6[,6])
M2(mod_Survey)

**Comment by philchalmers** [comment]
Can you describe why this behaviour is unexpected? Survey weights are used to evaluate more optimal parameter estimates given population demographic information via weights. Fit statistics like M2 are evaluating whether the current data were plausibly obtained according to the structure implied by the model. If the model parameters were happen to be chosen by a population with very different characteristics (i.e., the weights have a large impact) then the current data should seem to fit less in accordance with this structure.

**Comment by dcoven** [comment]
Good point. The reason I didn’t expect this is that I’m using sampling weights to work with expected cell probabilities, rather than true population samples.

 

Do you know if there is another way to tweak MIRT to work with probabilities for response patterns, rather than sample data?

 

Thanks for your time!

 

 

Daniel Coven

**Comment by philchalmers** [comment]
What you did was correct; the weights correspond to unique response patterns by weighting by some expected probability according to the pattern in the population. So I'm not quite sure what you're looking for here. In any event, I don't see this as an issue at this point, so I'll close this for now.
