### ISSUE TITLE
small coding mistake

### ISSUE THREAD

**Issue by jessekps** [philchalmers/mirt#179]
Hi,

I was walking through the mirt code for a different reason but I saw this line that appears to be a mistake. Pretty sure you meant the `== 2L` to be outside the brackets.

line 353 in multipleGroup.r

`if(sum(invariance.check == 2L) && length(constrain) == 0){`

**Comment by philchalmers** [comment]
Thanks, it looks like refinance of an old coding approach that was using a different mechanism. The `sum()` doesn't actually do anything now since it gets coerced into a logical automatically, but I'll patch the code since this does look a little weird.
