### ISSUE TITLE
Error in checkAtAssignment("NULL", "nfact", "integer") :    ‘nfact’ is not a slot in class “NULL”

### ISSUE THREAD

**Issue by neil-rubens** [philchalmers/mirt#18]
p.s. Thanks so much for the great package (and nice documentation).

Would very much appreciate help with the following.

I get an error:

``` r
Error in checkAtAssignment("NULL", "nfact", "integer") : 
  ‘nfact’ is not a slot in class “NULL”
```

When executing:

``` r
dat = structure(list(V1 = c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L), V2 = c(1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L), V3 = c(1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L
), V4 = c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 0L, 0L, 0L, 0L, 0L, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA), V5 = c(1L, 1L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 0L, 0L, 
0L, NA, NA, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L)), .Names = c("V1", "V2", 
"V3", "V4", "V5"), row.names = c(NA, 50L), class = "data.frame")

library(mirt)
mod1 <- mirt(dat, 1)
```

**Comment by psyguy** [comment]
Hi @philchalmers ,
Is there any way to handle/ignor this error?

Actually, to select the best model fit I'm doing exploratory IRT by fitting confirmatory models (i.e. I have defined factor loadings via `mirt.model`) to different groups, and do majority voting to select the best model based on information criteria e.g. AIC. In some groups all people have zero responses to certain items, and these all-zero items differ from group to group. For instance, items 7 and 8 are always zero in group 1, and items 3 and 4 in group 2.

Is there any way to get over this issue? The models are graded btw.

Thanks in advance!

**Comment by philchalmers** [comment]
@psyguy if you're fitting models with single-group estimation techniques (like `mirt`) then no, there's no logical fix to the problem since the parameters won't be identified without sufficient item variability. This can generally be overcome with `multipleGroup()` though, if you frame your mulit-group questions that way. 

Also, please use the `mirt-package` forum for general Q&As, or open a new issue if you think a coding bug is present.

**Comment by psyguy** [comment]
Thanks for the reply. I'll post new questions on the forum and keep here for bug reports/feature requests only.
Also, many many thanks for the package!
