### ISSUE TITLE
Issue while installing mirt package on rhel 7.8 version

### ISSUE THREAD

**Issue by mukhendra** [philchalmers/mirt#181]
Hi Phil,

Please find the below description steps, while installing gcc version

After updating gcc/g++ version from 4.8.5 to 9.3.0. Still I'm getting error while installing mirt package.
For reference gcc version:
image
![image](https://user-images.githubusercontent.com/40772418/82479178-a7206200-9aef-11ea-839f-e24bb228fa19.png)

Error
![image](https://user-images.githubusercontent.com/40772418/82479086-87893980-9aef-11ea-92ab-c847e8063703.png)

Regards,
Mukhendra

**Comment by philchalmers** [comment]
The error seems to be that `-lgfortran` cannot be located. Are you somehow missing FORTRAN compilers (i.e., `gfortran`), or perhaps it's also out of date? Can't say I've ever seen that error before.

**Comment by seonghobae** [comment]
A lot of the RHEL packages tend to out of date with stability issues (See https://access.redhat.com/security/updates/backporting). You can try to ```yum install gcc-gfortran```, but It will get 4.x version gcc and gfortran.
