### ISSUE TITLE
supporting broom, df.residual method and pooling model estimation (mice::pool) from multiple imputation

### ISSUE THREAD

**Issue by tingjhenjiang** [philchalmers/mirt#187]
Hello,
I would like to apply mirt analysis on multiple imputated survey datasets.
After I got mirt models for differently imputed datasets, I tried to pool the results by R package pool, but in vein.
There is a discussion at [the github page of R package mice](https://github.com/stefvanbuuren/mice/issues/242).
Can you add some S3methods or S4methods of broom::glance(), broom:tidy(), df.residual() to a mirt model ( e.g., class SingleGroupClass )?
You might check [tidymirt project](https://github.com/datacamp/tidymirt) and the readme page of [mice::pool()](https://www.rdocumentation.org/packages/mice/versions/3.9.0/topics/pool).

Thank you!

**Comment by seonghobae** [comment]
Unfortunately, mirt already has a multiple imputation function.

**Comment by tingjhenjiang** [comment]
> Unfortunately, mirt already has a multiple imputation function.

hello,
Do you mean [mirt::averageMI](https://rdrr.io/cran/mirt/man/averageMI.html) ? I think it is not straightforward according to the given example.

**Comment by philchalmers** [comment]
Thanks for the suggestion. Do you have suggestions as to what coding work would be required in order for mirt to behave nicely with `broom`? I'm not sure what would be required to implement an S3 method for broom to work with (I don't have interest in adding broom as a dependency). Thanks.
