### ISSUE TITLE
Apply scaling D factor (1.702) to Slope estimates?

### ISSUE THREAD

**Issue by state-o-flux** [philchalmers/mirt#199]
I'm wondering if it's possible to apply the scaling D factor to alpha parameter estimates in order to estimate the logistic item response model.

**Comment by philchalmers** [comment]
You can just apply the 1.7 constant after the model has been fitted to each parameter estimate (where applicable). There's really no need to do this in the estimation engine itself.

**Comment by state-o-flux** [comment]
Thanks, this works but then it won't be applied when running fscores(mirt_model) as the inherited model won't actually have changed.

**Comment by philchalmers** [comment]
The factor score computations would be invariant to a rescaling parameter like D. So even if you included this at the time of estimation the factor scores would be exactly the same under either parameterized scaling.
