### ISSUE TITLE
Implementing a CLI to run mirt

### ISSUE THREAD

**Issue by tlecarrour-ee** [philchalmers/mirt#203]
Hi,

**Disclaimer:** I checked mirt and mirtCAT documentation, but could not find the information I was looking for, but I might have missed it!

I've been assigned the task to implement a CLI to "replace" a mirtCAT instance, but I don't know where to start!
Is there any example in the source code I could check out or any other project implementing this?

Any help or link would be highly appreciated!

Tanguy

**Comment by philchalmers** [comment]
Could you describe what you're trying to do first exactly? Also, this is the `mirt` repo, not `mirtCAT`, so I'll close this as it doesn't seem relevant to this repo.

**Comment by tlecarrour-ee** [comment]
Hi @philchalmers

Thanks for your answer! Sorry if this is not the proper place to ask my question, but `mirtCAT`'s Github did not look like the proper place to ask that question.

I'm working for a team that uses `mirtCAT,` but I have to integrate it in a bigger application written in Python and Javascript. 

My goal is to have a frontend (Python/JS) sends the answers to a backend (R/mirt). Having a CLI (interactive question/answer) is my first step to make sur that I can interact with the `mirt` library in a stateless fashion. But I may have totally missed what `mirt` is supposted to be (the logic) and what is its relation to `mirtCAT` (the frontend).

Thank you so much for your time and answers!

**Comment by tlecarrour-ee** [comment]
Hi @philchalmers 

Sorry to bother you again, but… apparently you closed this issue for good. So where do you suggest I ask my question?!

Thank for your time and help.
