### ISSUE TITLE
 estfun.AllModelClass() for QMCEM

### ISSUE THREAD

**Issue by tzoltak** [philchalmers/mirt#210]
Hi!
I wanted to use Vuong's test implemented in the _nonnest2_ package to compare two _mirt_ models. Unluckily these models include up to 10 factors and because of this I estimated them using QMCEM. This however makes it impossible to use Vuong test as its implementation relies on calling `estfun.AllModelClass()` from _mirt_ and it supports only models estimated with EM or BL.
Would it be possible to implement `estfun.AllModelClass()` also for models estimated with QMCEM or MCEM?

**Comment by philchalmers** [comment]
It would take a substantial amount of work to do this, but it likely isn't impossible given the current code base. I'll add it to the long-term TODO list, but I'll close this as an issue for now. Thanks for the suggestion.
