### ISSUE TITLE
itemfit using PV_Q1*

### ISSUE THREAD

**Issue by thersites9** [philchalmers/mirt#219]
Hi,

I just wanted to let you know that the item fit procedure in `itemfit()` using PV_Q1* throws an error using mirt version 1.35.1: 

**Error in p.adjust(p.Q1, method = p.adjust) :  argument "p.adjust" is missing, with no default**

````
mirt::itemfit(mirt::mirt(Science, 1), fit_stats = "PV_Q1*", p.adjust = "BH")
````

However, the non-"*" version (i.e., "PV_Q1") works fine.

Best wishes, Timo

**Comment by philchalmers** [comment]
Thanks, Timo. Not sure how this got buy the test releases, but should be patched now.

**Comment by thersites9** [comment]
I appreciate the quick fix!

Timo
