### ISSUE TITLE
Feature request: provide EMhistory in `mirt` output

### ISSUE THREAD

**Issue by netique** [philchalmers/mirt#225]
In `EM.group`, there is `EMhistory` matrix that I think is very useful and could be part of a fitted object produced by `mirt`. For some `SE.type`s, it is already returned by `EM.group`, but then it is sadly not carried any further (from what I see). It would be nice to have it for all EM fits somewhere in `fit@Internals`.

Many thanks for considering the feature!

**Comment by philchalmers** [comment]
Seems reasonable to me. You can now add `technical = list(storeEMhistory=TRUE)` during estimation, and extract the history via `extract.mirt(mod, 'EMhistory')`
