### ISSUE TITLE
read.mirt

### ISSUE THREAD

**Issue by cakinnnn** [philchalmers/mirt#229]
Hi Phil,

I have trouble with read.mirt.  I want to use read. mirt command to equate test with plink. However, when I write the command, I get the error "Error: plink package is not available. Please install."  (I installed the plink and mirt packages already).

Could you please help me with this issue?

**Comment by philchalmers** [comment]
It's not the mirt package we're looking for, it's the `plink`  package.

**Comment by cakinnnn** [comment]
Could you see the pdf document which I attached?
I wrote;

library(plink)
sessionInfo()

**Comment by cakinnnn** [comment]
By the way, when I used, the codes which are in the mirt package. I got the same error. 

> library(mirt)
> library(plink) #if the package doesn't installed, I got an warning about that. 
> mod2 <- mirt(Science, 1)
> plinkpars <- read.mirt(mod2)
Error: plink package is not available. Please install.
> plot(plinkpars)
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'plot': object 'plinkpars' not found
> plot(mod2, type = 'trace')

**Comment by philchalmers** [comment]
No, the PDF is not attached. Ideally a reprex would be best to report, but failing that printing the relevant information via copy-paste is fine.

**Comment by philchalmers** [comment]
```r
library(plink) #if the package doesn't installed, I got an warning about that.
```

`library()` doesn't install a package, it loads it. You need to use `install.packages()` to install `plink` first before you use `library()`.
