### ISSUE TITLE
Are estimated covariances between factors incorporated into  M2 fit statistics?

### ISSUE THREAD

**Issue by kephartg** [philchalmers/mirt#240]
Hi Phil,

I also posted this on the mirt google page, but thought I should post it here as well as I suspect a problem with the fit statistics generated by the m2 command in mirt for a 7-factor graded response model.  In particular, I am concerned that estimated covariances between factors may not be properly incorporated into the computation of residual matrix used for M2 fit statistics. 

Here is my mirt model, estimated on a sample of about 1100 observations. The items are all ordinal with 6 response categories:
"   resDom = res8, res11, res13, res15
    proDom = pro2, pro3, pro4, pro5, pro7
    intDom = int1, int2, int3, int4, int5, int7, int8, int10
    actDom = act2, act5, act6, act8, act12
    socDom = soc3, soc6, soc7, soc8, soc9
    heaDom = hea1, hea3, hea4, hea6, hea7
    disDom = dis3, dis4, dis5, dis6
    COV=resDom*proDom*intDom*actDom*socDom*heaDom*disDom"

Estimation:
mirt(data, model, itemtype='graded', method='MHRM')

The discrimination parameters and associated standardized loadings look good:
Standardized factor loadings:
`      resDom proDom intDom actDom socDom heaDom disDom    h2
res8   0.824  0.000  0.000  0.000  0.000  0.000  0.000 0.678
res11  0.862  0.000  0.000  0.000  0.000  0.000  0.000 0.742
res13  0.776  0.000  0.000  0.000  0.000  0.000  0.000 0.602
res15  0.805  0.000  0.000  0.000  0.000  0.000  0.000 0.649
pro2   0.000  0.733  0.000  0.000  0.000  0.000  0.000 0.537
pro3   0.000  0.858  0.000  0.000  0.000  0.000  0.000 0.736
pro4   0.000  0.735  0.000  0.000  0.000  0.000  0.000 0.540
pro5   0.000  0.738  0.000  0.000  0.000  0.000  0.000 0.544
pro7   0.000  0.734  0.000  0.000  0.000  0.000  0.000 0.539
int1   0.000  0.000  0.779  0.000  0.000  0.000  0.000 0.607
int2   0.000  0.000  0.777  0.000  0.000  0.000  0.000 0.604
int3   0.000  0.000  0.843  0.000  0.000  0.000  0.000 0.711
int4   0.000  0.000  0.808  0.000  0.000  0.000  0.000 0.653
int5   0.000  0.000  0.803  0.000  0.000  0.000  0.000 0.645
int7   0.000  0.000  0.833  0.000  0.000  0.000  0.000 0.694
int8   0.000  0.000  0.808  0.000  0.000  0.000  0.000 0.653
int10  0.000  0.000  0.775  0.000  0.000  0.000  0.000 0.601
act2   0.000  0.000  0.000  0.730  0.000  0.000  0.000 0.533
act5   0.000  0.000  0.000  0.747  0.000  0.000  0.000 0.558
act6   0.000  0.000  0.000  0.807  0.000  0.000  0.000 0.651
act8   0.000  0.000  0.000  0.848  0.000  0.000  0.000 0.719
act12  0.000  0.000  0.000  0.817  0.000  0.000  0.000 0.667
soc3   0.000  0.000  0.000  0.000  0.719  0.000  0.000 0.517
soc6   0.000  0.000  0.000  0.000  0.766  0.000  0.000 0.586
soc7   0.000  0.000  0.000  0.000  0.761  0.000  0.000 0.579
soc8   0.000  0.000  0.000  0.000  0.726  0.000  0.000 0.528
soc9   0.000  0.000  0.000  0.000  0.807  0.000  0.000 0.651
hea1   0.000  0.000  0.000  0.000  0.000  0.843  0.000 0.711
hea3   0.000  0.000  0.000  0.000  0.000  0.709  0.000 0.503
hea4   0.000  0.000  0.000  0.000  0.000  0.654  0.000 0.428
hea6   0.000  0.000  0.000  0.000  0.000  0.646  0.000 0.418
hea7   0.000  0.000  0.000  0.000  0.000  0.747  0.000 0.558
dis3   0.000  0.000  0.000  0.000  0.000  0.000  0.804 0.647
dis4   0.000  0.000  0.000  0.000  0.000  0.000  0.728 0.530
dis5   0.000  0.000  0.000  0.000  0.000  0.000  0.802 0.643
dis6   0.000  0.000  0.000  0.000  0.000  0.000  0.837 0.701`

As expected, based on the theoretical model on which the instrument is based, the domains are correlated with each other and, no, neither theory nor statistical tests suggest that any should be collapsed.
Factor correlations: 
       resDom proDom intDom actDom socDom heaDom disDom
resDom  1.000                                          
proDom  0.764  1.000                                   
intDom  0.617  0.674  1.000                            
actDom  0.678  0.676  0.752  1.000                     
socDom  0.781  0.744  0.753  0.783  1.000              
heaDom  0.585  0.696  0.833  0.858  0.739  1.000       
disDom  0.625  0.596  0.496  0.590  0.542  0.511 

The M2 fit statistics for this model, with the possible exception of the RMSEA, identify potential concerns with model fit:

M2(model, type = "M2*", QMC=T, calcNull = T):
            M2   df     p      RMSEA         RMSEA_5     RMSEA_95    SRMSR     TLI          CFI
stats 2690.236 429 0 0.07192124 0.06929696 0.0745002 0.339581 0.73082 0.7623905

These fit statistics are poor compared to the corresponding model in Lavaan (which treated the items as ordinal, and was estimated with DWLS): RMSEA=0.057 (90% CI 0.055–0.060), SRMR= 0.039, CFI=0.951. While I don’t expect them to be the same, such a large discrepancy is surprising.

To see why the mirt model is fitting poorly, I obtained the residual matrix used to compute the SRMSR statistic, part of which I have pasted below.  All the residuals between items within each domain are small, while the residuals for items between domains are large. 

This leads me to wonder if the estimated covariances between domains are being adequately incorporated into the computation of the residual matrix ? 

Part of residual matrix:
              res8        res11        res13     res15          pro2        pro3        pro4        pro5      pro7
res8            NA           NA           NA        NA            NA          NA          NA          NA        NA
res11  0.005898772           NA           NA        NA            NA          NA          NA          NA        NA
res13 -0.033083701  0.049244206           NA        NA            NA          NA          NA          NA        NA
res15 -0.064981595 -0.001314912 -0.003779464        NA            NA          NA          NA          NA        NA
pro2   0.338268057  0.308758405  0.298456524 0.3617046            NA          NA          NA          NA        NA
pro3   0.445041893  0.448666562  0.391390770 0.4743504  0.0307886389          NA          NA          NA        NA
pro4   0.356645286  0.345495456  0.330637715 0.3774794  0.0235262091  0.03322430          NA          NA        NA
pro5   0.412233387  0.365155596  0.344367562 0.3708618 -0.0308957446 -0.04386380 -0.02559015          NA        NA
pro7   0.442298579  0.502829140  0.432504370 0.4946823 -0.0003495851 -0.06076152 -0.06702194 -0.06044112        NA

**Comment by philchalmers** [comment]
Thanks very much for the report. This was indeed an implementation bug when using QMC integration post-convergence. For whatever reason I forgot to include the latent mean/variable shift in the integration grid after the models were fitted, and `M2()` was one such area where this makes a large difference. I've added this into the package now to fix the problem, which also appeared in `fscores()` and `residuals()`. Quite frustrating, but I'm glad this was detected. 

Feel free to install and close the issue if the results look more acceptable on your end! Thanks again, and my apologies for the implementation error.

**Comment by kephartg** [comment]
Thanks Phil for addressing this so quickly, and I am glad I was able to contribute in a small way to improve the package. It is always scary to discover an error on one’s code, but it happens.

 I suspect the change will make a pretty big difference in the fit stats, and I also keen to see how it affects the scores.  I have been a bit puzzled by the magnitude of differences between EAP and MAP scores and SEs I am seeing in my data.

Best,
George
------------------------------------
George Kephart, PhD
Professor
Graduate Coordinator
Department of Community Health and Epidemiology and the School of Health Administration
Dalhousie Univers

Visiting Professor, Umea University, Sweden




On Jun 30, 2023, at 1:28 PM, Phil Chalmers ***@***.******@***.***>> wrote:

CAUTION: The Sender of this email is not from within Dalhousie.


Thanks very much for the report. This was indeed an implementation bug when using QMC integration post-convergence. For whatever reason I forgot to include the latent mean/variable shift in the integration grid after the models were fitted, and M2() was one such area where this makes a large difference. I've added this into the package now to fix the problem, which also appeared in fscores() and residuals(). Quite frustrating, but I'm glad this was detected.

Feel free to install and close the issue if the results look more acceptable on your end! Thanks again, and my apologies for the implementation error.

**Comment by kephartg** [comment]
If you are asking me to test your corrected code on GitHub, I don't really know  how to do that.   I can't even figure out where the package scripts are stored :)

**Comment by kephartg** [comment]
Hi Phil.  I am having trouble installing your updates from GitHub using devtools, as R can't find the path to gfortran on my computer.  Not your problem, but I am stuck right now trying to fix it.  Have you pushed the changes through to cran? It does show a published date of yesterday, so I reinstalled mirt and re-ran the code.  I am getting exactly the same results as in my post above, so it appears that I do not have your updates installed.

**Comment by philchalmers** [comment]
It's likely you need to install Rtools and include the option set the binaries into your Windows path (https://cran.r-project.org/bin/windows/Rtools/). After that it should install, where the C++ files will be compiled before it's installed. `devtools::install_github()` makes this approach reasonably straightforward, provided that it can find the correct binary files. I haven't pushed this to CRAN yet.

If you can't get it working no worries, the simulated example I created showed notable improvements over the previous version so I'm sure it's working as it was originally supposed to.

**Comment by kephartg** [comment]
Hi Phil,

I succeeded in getting your revised code installed from github. Resolving the problem on MacOS was a headache – lots of online advice, much of it wrong.

Anyway, I have re-run the models and fit statistics .  Unfortunately, while the numbers have changed, they are still not plausible. Before the code change, the residual matrix was plausible within domains, but implausible between domains.  The patterns suggested that the covariances were not being incorporated  into the residual matrix, as they were what I would expect to see of the factors were treated as orthogonal.  With the revised code, I get the following fit statistics:

           M2  df p      RMSEA    RMSEA_5   RMSEA_95     SRMSR       TLI      CFI
stats 4114.97 429 0 0.09182484 0.08923295 0.09434844 0.2343355 0.5584481 0.610235

And a residual matrix with the following pattern (I just pasted residuals for the first two domains).  Now the residuals are high within domains, and lower between domains:

M2(mod_prism1, type = "M2*", QMC=T, residmat = T)
              res8       res11       res13        res15         pro2          pro3         pro4         pro5         pro7
res8            NA          NA          NA           NA           NA            NA           NA           NA           NA
res11 -0.213983915          NA          NA           NA           NA            NA           NA           NA           NA
res13 -0.274813653 -0.18541183          NA           NA           NA            NA           NA           NA           NA
res15 -0.304215398 -0.23032806 -0.26175277           NA           NA            NA           NA           NA           NA
pro2  -0.095334980 -0.12146112 -0.11945605 -0.059384072           NA            NA           NA           NA           NA
pro3  -0.084724385 -0.08590117 -0.11999631 -0.035301268  0.092686747            NA           NA           NA           NA
pro4  -0.076435750 -0.09238923 -0.09031035 -0.051868938  0.092956095  0.0966521308           NA           NA           NA
pro5  -0.028946863 -0.08106201 -0.07748778 -0.059736361  0.038309587  0.0188754559  0.043861535           NA           NA
pro7   0.006485488  0.05483639  0.01523141  0.075160502  0.057087652 -0.0005550135 -0.012084744 -0.007141465           NA

To provide more information on the problem I fit the model with just the first two domains so I could compare results with and without QMC=T:
respro_mdl <- "resDom = res8, res11, res13, res15
               proDom = pro2, pro3, pro4, pro5, pro7
               COV=resDom*proDom"

respro_mirt_mdl <- mirt.model(respro_mdl, itemnames=colnames(resprodata))
respro_prism_em <- mirt(resprodata, respro_mirt_mdl, itemtype='graded')

And then compared fit statistics with and without QMC=T. Without QMC=T the results look reasonable:
> M2(respro_prism_em, type="C2")
            M2 df p      RMSEA    RMSEA_5   RMSEA_95      SRMSR       TLI       CFI
stats 156.0627 26 0 0.07006523 0.05966371 0.08082133 0.05181143 0.9761244 0.9827565
> M2(respro_prism_em, type = "C2", residmat = T)
              res8        res11        res13        res15         pro2        pro3         pro4        pro5 pro7
res8            NA           NA           NA           NA           NA          NA           NA          NA   NA
res11 -0.005450355           NA           NA           NA           NA          NA           NA          NA   NA
res13 -0.031575432  0.025996801           NA           NA           NA          NA           NA          NA   NA
res15 -0.052956985 -0.009942327 -0.009729968           NA           NA          NA           NA          NA   NA
pro2  -0.064388297 -0.116150305 -0.082039928 -0.018789860           NA          NA           NA          NA   NA
pro3  -0.024236095 -0.055866434 -0.052701520  0.036118782  0.005328706          NA           NA          NA   NA
pro4  -0.038304603 -0.079462806 -0.046035307 -0.004027922  0.010464428  0.01849414           NA          NA   NA
pro5   0.029937483 -0.045499471 -0.013386945  0.008498288 -0.018303990 -0.02837802 -0.005526029          NA   NA
pro7   0.054592433  0.077766571  0.069274410  0.132510895 -0.016536940 -0.06792091 -0.078099130 -0.04764395   NA

But with QMC=T the results are very different and implausible:
> M2(respro_prism_em, type="C2", QMC=T)
            M2 df            p      RMSEA    RMSEA_5   RMSEA_95     SRMSR       TLI       CFI
stats 135.2459 26 1.110223e-16 0.06421388 0.05373212 0.07506964 0.1442869 0.9799457 0.9855163

> M2(respro_prism_em, type = "C2", QMC=T, residmat = T)
             res8       res11       res13     res15      pro2      pro3      pro4     pro5 pro7
res8           NA          NA          NA        NA        NA        NA        NA       NA   NA
res11 -0.09542821          NA          NA        NA        NA        NA        NA       NA   NA
res13 -0.13127502 -0.06712140          NA        NA        NA        NA        NA       NA   NA
res15 -0.15243582 -0.10270596 -0.11129253        NA        NA        NA        NA       NA   NA
pro2   0.07238578  0.03738692  0.04654887 0.1100570        NA        NA        NA       NA   NA
pro3   0.10999737  0.09738075  0.07296439 0.1617030 0.2050114        NA        NA       NA   NA
pro4   0.09757982  0.07293176  0.08171088 0.1239432 0.2027680 0.2164552        NA       NA   NA
pro5   0.16362340  0.10361456  0.11229670 0.1345700 0.1685283 0.1644276 0.1800744       NA   NA
pro7   0.19041295  0.23019132  0.19699082 0.2605092 0.1758106 0.1305184 0.1126517 0.137718   NA

So, as you have noted the problem is clearly with the QMC option.  

Let me know if there is anything else I can do to help.

**Comment by philchalmers** [comment]
Thanks for checking and working through the MacOS compiler pain! 

It looks like the fix added one extra transpose to the `theta` shifts, which for the Cholesky decomposition is equivalent to taking the inverse 2x. I just pushed the fix to Github now. Here's what I get with my test case:

```r
library(mirt)
a <- matrix(c(rlnorm(10,.2,.3), numeric(20), rlnorm(10,.2,.3)), ncol=2)

sigma <- matrix(c(1,.8,.8,1),2)

# for the graded model, ensure that there is enough space between the intercepts,
# otherwise closer categories will not be selected often (minimum distance of 0.3 here)
diffs <- t(apply(matrix(runif(20*4, .3, 1), 20), 1, cumsum))
diffs <- -(diffs - rowMeans(diffs))
d <- diffs + rnorm(20)

dat <- simdata(a, d, 5000, itemtype = 'graded', sigma = sigma)

mod <- mirt(dat, "F1 = 1-10
                  F2 = 11-20
                  COV=F1*F2")

modQMC <- mirt(dat, "F1 = 1-10
                  F2 = 11-20
                  COV=F1*F2", method = 'QMCEM')

anova(mod, modQMC) # same fit
> mod    245169.9 245507.2 245400.6 245828.2 -122484.0             
> modQMC 245169.6 245506.9 245400.3 245827.9 -122483.8 0.298  0 NaN

M2(mod)
>             M2  df         p RMSEA RMSEA_5    RMSEA_95       SRMSR      TLI CFI
> stats 92.80424 109 0.8666607     0       0 0.003991512 0.009354053 1.001279   1
M2(mod, QMC=TRUE)

>            M2  df         p RMSEA RMSEA_5    RMSEA_95       SRMSR      TLI CFI
> stats 92.37423 109 0.8735268     0       0 0.003866112 0.009359425 1.001313   1

```

**Comment by kephartg** [comment]
I just checked as well, and the results with and without QMC=T are nearly identical in my data:

`> M2(respro_prism_em, type = "C2", QMC=T)
            M2 df p      RMSEA    RMSEA_5   RMSEA_95      SRMSR       TLI       CFI
stats 155.8999 26 0 0.07002138 0.05961935 0.08077814 0.05166928 0.9761542 0.9827781
> M2(respro_prism_em, type = "C2")
            M2 df p      RMSEA    RMSEA_5   RMSEA_95      SRMSR       TLI       CFI
stats 156.0627 26 0 0.07006523 0.05966371 0.08082133 0.05181143 0.9761244 0.9827565
> `

I will close this issue and then post a link to my entry on the Google groups page so  that the resolution is documented there as well.

Thanks so much for your very prompt attention to this issue, especially over Canada Day weekend with the very hot weather in Toronto.
