### ISSUE TITLE
Unexpected warning message in 'M2' function

### ISSUE THREAD

**Issue by fedebacchi** [philchalmers/mirt#251]
Hi, I am currently working on my PhD thesis and the first part of the research is about the estimation of MIRT models. For this reason, I am using 'mirt' package which has a plenty of useful functions and desirable features. However, I am experiencing some trouble while computing limited information test statistics via 'M2' function. No matter if I include survey weights and if I increase the number of quadrature points, I always get the following warning message:
```
## Warning in pchisq(X2, df = df, ncp = lambda): pnchisq(x=4.19856e+06, f=406,
## theta=4.19856e+06, ..): not converged in 1000000 iter.
```
As you can see in the attached pdf file ([mirt_help_upd.pdf](https://github.com/philchalmers/mirt/files/15189703/mirt_help_upd.pdf)), it does not seem to be a matter related to the big sample size. Could you please help me in finding the source of the problem?

**Comment by philchalmers** [comment]
This indicates that the CIs for the RMSEA statistic could not be computed given how large the misfit was. It's possible for these estimates to fail given their root-solving nature, and should not be related to either survey weights or quadrature as it has to do with chi-squared distribution function given the lack of fit statistics returned from M2().

**Comment by fedebacchi** [comment]
Thank you for your answer. So, I cannot rely on the estimated values for the CIs of the RMSEA but I can still rely on all the other statistics, including the point estimate of the RMSEA.

**Comment by philchalmers** [comment]
Correct
