### ISSUE TITLE
complete missing and fscore for multigroup models

### ISSUE THREAD

**Issue by Keddeko** [philchalmers/mirt#252]
Hi there
I have a dataset with design based complete missings for some rows. Instead of merging with a PID or similar, I have no problem getting the ability estimates with fscores(mirt_model, full.scores.SE = TRUE) for the full matrix with complete NAs for some rows, but when I make a multigroup model with multipleGroup and try to retrieve the results with full.scores.SE or full.scores in the same way I get the following: `[<-`(`*tmp*`, completely_missing, , value = NA) : 
  subscript out of bounds

If I on the other hand make full row deletion for the observations with complete missings it works fine. But, should the fscores(full.scores=TRUE) not work for both the multipleGroup and for mirt objects also in cases with complete missings? 

It would be nice in order to have a full dataset (with NAs naturally for rows with complete missings). 
Best and thanks for a cool and well documented package ! '
Christian

**Comment by philchalmers** [comment]
Hi Christian,

Thanks for the report. Does this issue still exist on the current dev version here on Github? If so, could you please provide a brief reprex demonstrating the issue so that it can be patched? Thanks in advance.

**Comment by Keddeko** [comment]
Dear Phil
I have tried the current dev verion and it solved the issue - thanks 
Best regards
Christian
