### ISSUE TITLE
Acceleration and EMhistory

### ISSUE THREAD

**Issue by winniewytse** [philchalmers/mirt#257]
Hi @philchalmers, thank you for providing the option to extract the iteration history of the EM algorithm, which is very helpful in identifying items that hinder model convergence. We usually compare the changes in parameter estimates between the last two rows in EM history and flag items with changes larger than the selected tolerance. 

Recently, we discovered situations where mirt concludes model convergence, but comparing the last two rows in the EM history suggests items with changes larger than the tolerance. 

After working with the `EM.group()` function, we noticed that `longpars` are further modified in the [acceleration step](https://github.com/philchalmers/mirt/blob/e4ee5f5bec114b895c453fea0573e1d6c2e616c7/R/EMstep.group.R#L331) every 3 iterations. But the unmodified version of `longpars` is [stored in the EMhistory](https://github.com/philchalmers/mirt/blob/e4ee5f5bec114b895c453fea0573e1d6c2e616c7/R/EMstep.group.R#L317). 

Is it possible to store `longpars` after the acceleration step to reflect what mirt uses in evaluating model convergence? 

Thanks for your time and consideration!

Winnie

**Comment by philchalmers** [comment]
Yes, and this should have been the default behavior. I've patched this issue on the dev version. Thanks for the report!

**Comment by winniewytse** [comment]
Thanks so much, @philchalmers for the prompt response and update!
