### ISSUE TITLE
[Feature Request] Constraints for homogeneous DIF

### ISSUE THREAD

**Issue by choisycorentin** [philchalmers/mirt#258]
Hello,

I have recently tried to fit a partial credit model using mirt. Specifically, I am trying to model:

-  The effect of a binary group variable (0/1) on the latent variable (i.e. the difference in average level in the latent variable between the two groups)
- DIF on a specific polytomous item with four response categories. 

For this, I would like to estimate an additional parameter for the difference in average latent variable level between two levels of a binary group variable _X_ and parameters representing the difference in item threshold parameters between the two levels of _X_.

Let's say I wanted to compute such a model with mirt with DIF parameters specifically on item3 in a 4-item questionnaire, I believe this is achieved by the following command:

`model_example <- multipleGroup(data=data[,c("item1","item2","item3","item4")],itemtype="Rasch",model=1,group=data$group,invariance = c("item1","item2","item4","free_means"),SE=T)`

Indeed, if I'm not mistaken, the group effect parameter's value could be obtained with `coef(model_example)` by computing the difference in GroupPars: `coef(model_example)$'1'$GroupPars[1,"MEAN_1"]-coef(aaaa)$'0'$GroupPars[1,"MEAN_1"]`.
Conversely, the DIF parameters could be computed by: 
`dif_param_1 <- coef(aaaa)$'1'$item3[1,"d1"]-coef(aaaa)$'0'$item3[1,"d1"]
dif_param_2 <- coef(aaaa)$'1'$item3[1,"d2"]-coef(aaaa)$'0'$item3[1,"d2"]
dif_param_3 <- coef(aaaa)$'1'$item3[1,"d3"]-coef(aaaa)$'0'$item3[1,"d3"]`

However, I would specifically be interested in modeling homogeneous DIF _i.e._ the same model where `dif_param_1`, `dif_param_2` and `dif_param_3` are all constrained to be equal. More generally, this would mean being able to constrain all  between-group differences in threshold parameters to be equal per item.

Do you believe this to be possible with the current version of mirt or to be a possible addition ?

In any case, I hope I was I clear as possible and will be able to provide more explanation and/or toy datasets to test this feature if needed.
Thank you for your awesome work on mirt !

**Comment by philchalmers** [comment]
It sounds like what you're describing is a likelihood ratio testing approach between competing models. If you use the `invariance` argument you can specify which items should be constrained, which will constrain all item parameters to equality. Then `anova()` would be used to compute the LR statistic, along with the large sample chi^2 distribution and friends. Does this help?

**Comment by choisycorentin** [comment]
This is useful, but I think this isn't exactly what I was looking for, I'll get into more detail.

Let's say I have a questionnaire comprised of J=4 polytomous items numbered j=1,...,4 with response categories r=0,1,2,3 completed by i=1,...,N individuals. To compute latent variable measurement and item threshold parameters _delta_ estimates, I would compute a simple partial credit model:

![image](https://github.com/user-attachments/assets/6f224fbd-c406-447b-9f32-3723eea01301)

Which is achieved with mirt with `mirt(data=data[,c("item1","item2","item3","item4")], model=1, itemtype="Rasch", SE=T)`

Now if individuals in my data are divided into two groups (x=0 or x=1) and I wanted to estimate the value of _beta_ the effect of group membership on the latent variable _i.e._ the difference in average theta level between individuals with x=0 and individuals with x=1, I would compute:

![image](https://github.com/user-attachments/assets/96bf707b-55af-4468-8b29-c2f0501323ac)

Which (I believe) is achieved in mirt with: `multipleGroup(data=data[,c("item1","item2","item3","item4")],itemtype="Rasch",model=1,group=data$x,invariance = c("item1","item2","item3","item4","free_means"),SE=T)`

Adding to this, let's now say I have knowledge that item 3 is affected by either DIF or DSF induced by group membership, I would want to estimate the value of _gamma_ which is the effect of group membership on each threshold parameter of item 3 _i.e._ the difference in item 3 threshold parameter between group x=0 and group x=1. This means computing this PCM:

![image](https://github.com/user-attachments/assets/6eba4229-4c4d-460d-bdf5-9fd509607bfb)

With _gamma_ constrained to zero for items other than item 3. Now, for these _gamma_ parameters to model DIF effects, they would have to be all constrained to be equal, while them being freely estimated would mean they model DSF parameters. I managed to get these DSF parameters from `multipleGroup(data=data[,c("item1","item2","item3","item4")],itemtype="Rasch",model=1,group=data$x,invariance = c("item1","item2","item4","free_means"),SE=T)`, but I haven't managed to get them constrained to be equal.

Do you believe this to be achievable with mirt ?

**Comment by philchalmers** [comment]
I see, thanks for clarifying. What you are describing here is a different parameterization of what's already appearing in the multiple-group models. Your first equation is a  single group model (or equivalently, a multi-group model with all item and group parameters constrained to be equal), the second equation indeed is reflected by freeing the latent mean of the second group, while the third equation is expressed in terms of a deviation parameter than in terms of the observed intercept. So, if you want to obtain the $\gamma$s all you need is to find the difference of the resulting intercept terms. See below.

```{r}
library(mirt)

set.seed(12345)
a <- matrix(abs(rnorm(15,1,.3)), ncol=1)
d <- matrix(rnorm(15,0,.7),ncol=1)
d <- cbind(d, d-1, d-2)
itemtype <- rep('graded', nrow(a))
N <- 1000
dataset1 <- simdata(a, d, N, itemtype)
dataset2 <- simdata(a, d, N, itemtype, mu = .1, sigma = matrix(1.5))
dat <- rbind(dataset1, dataset2)
group <- c(rep('D1', N), rep('D2', N))

mod <- multipleGroup(dat, group=group, itemtype='Rasch',
                     invariance=c(colnames(dat)[-1], 'free_means'))
D1 <- coef(mod, simplify=TRUE)$D1
D2 <- coef(mod, simplify=TRUE)$D2

# these are the gammas for item 1
unname(D1$items[1,c('d1', 'd2', 'd3')] - D2$items[1,c('d1', 'd2', 'd3')])
```

You could do a simliar  logic with `wald()` as well, though this requires computing a suitable ACOV matrix first.

**Comment by choisycorentin** [comment]
This is indeed what I'm looking for, thanks. The only remaining interrogation I have is whether there could be a way to constrain all gammas for a given item to be equal between them, as with the solution you provided, this constraint isn't present (meaning I would consider the parameters I get from your example DSF parameters, and not DIF paramaters). This would mean being able to input a constraint that would lead to such a result in your example:
`unname(D1$items[1,c('d1')]-D2$items[1,c('d1')]) == unname(D1$items[1,c('d2')]-D2$items[1,c('d2')]) ==
 unname(D1$items[1,c('d3')]-D2$items[1,c('d3')])`

**Comment by philchalmers** [comment]
Probably the easiest way to do this is with a Wald test to evaluate whether the difference between the gammas are constant. This joint test works as a continuation from above:

```r
mod <- multipleGroup(dat, group=group, itemtype='Rasch',
                     invariance=c(colnames(dat)[-1], 'free_means'), SE=TRUE)  ## SE = TRUE  required
D1 <- coef(mod, simplify=TRUE)$D1
D2 <- coef(mod, simplify=TRUE)$D2

# these are the gammas for item 1
unname(D1$items[1,c('d1', 'd2', 'd3')] - D2$items[1,c('d1', 'd2', 'd3')])

wald(mod)
wald(mod, c("d1.7 - d1.144 = d2.8 - d2.145", "d1.7 - d1.144 = d3.9 - d3.146"))

           W df         p
1 0.09123388  2 0.9554079
```

If you're interested in a likelihood ratio approach you'd have to build the model directly with `createItem()` and go from there.

**Comment by choisycorentin** [comment]
I would actually not be looking to test whether gammas are equal, but to constrain them to be equal during model estimation so that `unname(D1$items[1,c('d1', 'd2', 'd3')] - D2$items[1,c('d1', 'd2', 'd3')])` gives me equal values right after computing the model. The reason we're doing this is because introducing the constraint during model estimation makes the estimation of other model parameters account for the equality of gammas. 

I'll take a look at `createItem()`, as it appears to be quite versatile.

**Comment by philchalmers** [comment]
I assume that the `createItem()` approach was sufficient, so I'll close this issue for now. Feel free to reopen if you're still having difficulties.
