### ISSUE TITLE
Warning messages: 1: In model.elements(model = model$x, itemtype = itemtype, factorNames = factorNames,  :   NAs introduced by coercion

### ISSUE THREAD

**Issue by arashmonem** [philchalmers/mirt#260]
I've been recently self-studying psychometria mainly item response theory and I wanted to practice what I've learned through the use of mirt package.
Here is what I think seems to be a problem with the mirt package 
I downloaded a data that contains 20000 DAAS-42 responses, the time it took each respondent to choose an answer and the order in which the items had been shown.
here is the data link: http://openpsychometrics.org/_rawdata/
I provided the code file in attachment and I get this error despite not having any NAs in data file
Warning messages:
1: In model.elements(model = model$x, itemtype = itemtype, factorNames = factorNames,  :
  NAs introduced by coercion
 I tried to resolve  this issue with the help of chat gpt and the only option that has been left is that if there is a problem with the package

**here is my code:**
library(mirt)

# Prepare your item and covariate data
depression_items <- DAAS_data[,c(7,13,28,37,46,49,61)]
anxiety_items <- DAAS_data[,c(4,10,19,25,43,55,58)]
stress_items <- DAAS_data[,c(1,16,22,31,34,40,52)]
DAAS_data[,c(127:172)]=NULL

combined_data=DAAS_data

# Assuming combined_data is already loaded and properly formatted
# Define item response columns explicitly
item_responses <- combined_data[, grep("A", names(combined_data))]

# Define covariates (response times and item orders)
covariates <- combined_data[, grep("E|I", names(combined_data))]

# Define the multidimensional IRT model using specific item indices
# The indices are used to reference the right items according to your provided lists
#model_formula <- 'Q3A=Depression,Q5A=Depression,Q10A=Depression,Q13A=Depression,Q16A=Depression,Q17A=Depression,Q21A=Depression,
                    #Q2A=anxiety,Q4A=anxiety,Q7A=anxiety,Q9A=anxiety,Q15A=anxiety,Q19A=anxiety,Q20A=anxiety,
                    #Q1A=stres,Q6A=stres,Q8A=stres,Q11A=stres,Q12A=stres,Q14A=stres,Q18A=stres'

model_formula<-'Depression=~Q3A+Q5A+Q10A+Q13A+Q16A+Q17A+Q21A
                Anxiety=~Q2A+Q4A+Q7A+Q9A+Q15A+Q19A+Q20A
                Stress=~Q1A+Q6A+Q8A+Q11A+Q12A+Q14A+Q18A
                totalscore=~Q1A+Q2A+Q3A+Q4A+Q5A+Q6A+Q7A+
                            Q8A+Q9A+Q10A+Q11A+Q12A+Q13A+Q14A+
                            Q15A+Q16A+Q17A+Q18A+Q19A+Q20A+Q21A+
                            Q22A+Q23A+Q24A+Q25A+Q26A+Q27A+Q28A+
                            Q29A+Q30A+Q31A+Q32A+Q33A+Q34A+Q35A+
                            Q36A+Q37A+Q38A+Q39A+Q40A+Q41A+Q42A'

# Fit the model using a graded response model with covariates
model <- mirt(item_responses, model = model_formula, itemtype = 'graded', covdata = covariates, method = "MCEM")
saveRDS(model,"IRT_graded_MCEM.rds")
# Extract model parameters
item_parameters <- coef(model, simplify = TRUE)

# Print the item parameters
print(item_parameters)

**Comment by philchalmers** [comment]
I doubt this is an issue with the package, though I can't confirm as the DAAS object is not available in your script. Could you indicate how this was read in and formatted? As it stands this is not fully reproducible.

**Comment by philchalmers** [comment]
Also, you're including lavaan-style syntax rather than mirt's. So you may want to see the `?mirt.model` documentation before proceeding.

**Comment by arashmonem** [comment]
thank you for answering in such short notice. 
data is from http://openpsychometrics.org/_rawdata/ but I processed it and saved it in a csv format removed the covariates I didn't want in the model here is the data:
[Uploading modified_data.csv…]
I'm not familiar with syntax styles will start learning them tomorrow thank you

**Comment by arashmonem** [comment]
[modified_data - Copy.csv](https://github.com/user-attachments/files/17465751/modified_data.-.Copy.csv)
I couldnt upload the full version but here is the first 1000 of the responses which I complied again and got the same error
