### ISSUE TITLE
Error messages occured during install what using a github repo.

### ISSUE THREAD

**Issue by seonghobae** [philchalmers/mirt#38]
please check this error messages.
![default](https://cloud.githubusercontent.com/assets/8172694/6598886/dec42dd2-c849-11e4-99ac-476b450e5717.png)

> session_info()
Session info--------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.1.2 (2014-10-31)
 system   x86_64, darwin13.4.0        
 ui       RStudio (0.98.1102)         
 language (EN)                        
 collate  ko_KR.UTF-8                 
 tz       Asia/Seoul                  

Packages------------------------------------------------------------------------------------------------
 package       * version     date       source                            
 bfa           * 0.3.1       2014-02-11 CRAN (R 3.1.0)                    
 bitops          1.0.6       2013-08-17 CRAN (R 3.1.0)                    
 car           * 2.0.22      2014-11-18 CRAN (R 3.1.2)                    
 CDM           * 4.0         2014-11-22 CRAN (R 3.1.2)                    
 coda            0.16.1      2012-11-06 CRAN (R 3.1.0)                    
 DEoptimR        1.0.2       2014-10-19 CRAN (R 3.1.1)                    
 devtools      * 1.6.1       2014-10-07 CRAN (R 3.1.1)                    
 evaluate        0.5.5       2014-04-29 CRAN (R 3.1.0)                    
 foreign       * 0.8.61      2014-03-28 CRAN (R 3.1.0)                    
 formatR         1.0         2014-08-25 CRAN (R 3.1.1)                    
 GPArotation   * 2014.11.1   2014-11-25 CRAN (R 3.1.2)                    
 httr            0.5         2014-09-02 CRAN (R 3.1.1)                    
 knitr           1.8         2014-11-11 CRAN (R 3.1.2)                    
 lattice       * 0.20.29     2014-04-04 CRAN (R 3.1.2)                    
 latticeExtra  * 0.6.26      2013-08-15 CRAN (R 3.1.0)                    
 lavaan        * 0.5.18.788  2015-03-01 local                             
 lsr           * 0.3.2       2014-01-31 CRAN (R 3.1.0)                    
 MASS          * 7.3.35      2014-09-30 CRAN (R 3.1.2)                    
 Matrix          1.1.4       2014-06-15 CRAN (R 3.1.2)                    
 meta          * 4.0.1       2014-11-19 CRAN (R 3.1.2)                    
 metafor       * 1.9.5       2014-11-24 CRAN (R 3.1.2)                    
 mirt            1.8.5       2015-03-11 Github (philchalmers/mirt@9f2eddb)
 mnormt          1.5.1       2014-06-30 CRAN (R 3.1.1)                    
 multilevel    * 2.5         2013-04-10 CRAN (R 3.1.0)                    
 mvtnorm       * 1.0.1       2014-11-13 CRAN (R 3.1.2)                    
 nlme          * 3.1.118     2014-10-07 CRAN (R 3.1.2)                    
 nnet            7.3.8       2014-03-28 CRAN (R 3.1.2)                    
 norm            1.0.9.5     2013-02-28 CRAN (R 3.1.0)                    
 pbivnorm        0.5.1       2012-10-31 CRAN (R 3.1.0)                    
 pcaPP         * 1.9.60      2014-10-22 CRAN (R 3.1.2)                    
 plyr          * 1.8.1       2014-02-26 CRAN (R 3.1.0)                    
 polycor         0.7.8       2010-04-03 CRAN (R 3.1.0)                    
 pracma        * 1.7.9       2014-11-15 CRAN (R 3.1.2)                    
 psych         * 1.4.8.11    2014-08-12 CRAN (R 3.1.1)                    
 psychometric  * 2.2         2010-08-08 CRAN (R 3.1.0)                    
 quadprog        1.5.5       2013-04-17 CRAN (R 3.1.0)                    
 RColorBrewer  * 1.0.5       2011-06-17 CRAN (R 3.1.0)                    
 Rcpp            0.11.3      2014-09-29 CRAN (R 3.1.1)                    
 RcppArmadillo   0.4.550.1.0 2014-11-28 CRAN (R 3.1.2)                    
 RCurl           1.95.4.4    2014-11-29 CRAN (R 3.1.2)                    
 rmeta         * 2.16        2012-10-29 CRAN (R 3.1.0)                    
 robustbase    * 0.92.2      2014-11-22 CRAN (R 3.1.2)                    
 rrcov         * 1.3.4       2013-08-26 CRAN (R 3.1.0)                    
 rrcovNA       * 0.4.4       2013-08-29 CRAN (R 3.1.0)                    
 rsm           * 2.7         2014-10-02 CRAN (R 3.1.1)                    
 rstudioapi      0.1         2014-03-27 CRAN (R 3.1.0)                    
 semTools      * 0.4.6       2014-10-03 CRAN (R 3.1.1)                    
 sfsmisc         1.0.26      2014-06-16 CRAN (R 3.1.0)                    
 stringr         0.6.2       2012-12-06 CRAN (R 3.1.0)                    
 TAM           * 1.2         2014-11-22 CRAN (R 3.1.2)                    
 tensor          1.5         2012-05-05 CRAN (R 3.1.0)                    
> 

Seongho Bae

**Comment by philchalmers** [comment]
Is this the whole output? I don't see an error. Just warnings that `ncores` is never used, because OSX doesn't support OpenMP.

**Comment by seonghobae** [comment]
Sorry, I had a mistake. Yes, that's warnings; not errors.
Anyway, You are right. MacOSX can not support OpenMP; But, MacOSX can support OpenMP via GCC compile. (http://harvest.readthedocs.org/en/latest/content/parsnp/installation.html)

**Comment by philchalmers** [comment]
Others have had issues the `Rcpp` and `RcppArmadillo` on Mac OSX, so maybe this link will help at a later time: http://www.thecoatlessprofessor.com/programming/rcpp-rcpparmadillo-and-os-x-mavericks-lgfortran-and-lquadmath-error
