### ISSUE TITLE
Request: Specify lbound and ubound in mirt

### ISSUE THREAD

**Issue by bwiernik** [philchalmers/mirt#41]
It would be very convenient to be able to specify upper and lower bounds for parameters when calling a model using mirt or other functions, similar to how priors can be specified. At present, the three-step process to extract pars='values', change the bounds, and pass the table back to the model can be rather cumbersome for coding.

Thanks!

**Comment by philchalmers** [comment]
Check the news file (https://github.com/philchalmers/mirt/blob/master/NEWS.md); this was added a little while back, but the latest version hasn't been released to CRAN yet. I'll probably do that in the next few weeks. Cheers.

**Comment by bwiernik** [comment]
Would it be possible to also add an option to specify these values for exploratory models?

**Comment by philchalmers** [comment]
That's a good suggestion. I'll look into it
