### ISSUE TITLE
Covariance Estimation Issue

### ISSUE THREAD

**Issue by katcast** [philchalmers/mirt#45]
Hello Phil,
I recently downloaded your latest version of “mirt” on GitHub (version 1.10.1), and I am running into a discrepancy when using this package on my PC versus on linux.  I’m fitting between-item MIRT 2PL/GPCM models for my data and am specifying to freely estimate the covariances between the dimensions using the “COV” option in the “mirt.model” syntax (e.g., COV=F1\*F2\*F3).  However, when I run on linux, all between-dimension covariances are always outputted as “0.25”, whereas when I run on my PC, the covariances are freely estimated as I specified them to be.  I’m including a simple example below (modified version of one of your examples in the R mirt documentation).  Do you know what could be causing this discrepancy?  I tried updating my version on R to the most recent version (3.2.1) on linux and then installing “mirt” from GitHub, but that did not resolve the problem.  Thank you very much for your help.
Sincerely,
Katherine 

Example
library(mirt)
set.seed(52486)
#simulate data
a <- matrix(c(
1.5,NA,NA,
0.5,NA,NA,
1.0,NA,NA,
NA,1.0,NA,
NA,1.5,NA,
NA,NA,0.5,
NA,NA,1.0,
NA,NA,1.0),ncol=3,byrow=TRUE)

d <- matrix(c(
-1.0,
-1.5,
1.5,
0.0,
3.0,
2.5,
2.0,
1.0),ncol=1,byrow=TRUE)

sigma      <- diag(3)
sigma[upper.tri(sigma)] <- sigma[lower.tri(sigma)] <- .8
items      <- rep('dich',8)
dataset    <- simdata(a,d,2000,items,sigma)

#analyses
model.1 <- mirt.model('
  F1 = 1-3
  F2 = 4-5
  F3 = 6-8
 COV = F1\*F2\*F3')

mod1 <- mirt(dataset, model.1, method = 'MHRM') 
coef(mod1,simplify=TRUE)$cov

Results from my PC
> coef(mod1,simplify=TRUE)$cov
      F1    F2 F3
F1 1.000    NA NA
F2 0.637 1.000 NA
F3 0.686 0.657  1

> mod1

Call:
mirt(data = dataset, model = model.1, method = "MHRM")

Full-information item factor analysis with 3 factor(s).
Converged within 0.001 tolerance after 197 MHRM iterations.
mirt version: 1.10.1 
M-step optimizer: NR 

Log-likelihood = -7691.483, SE = 0.021
AIC = 15420.97; AICc = 15421.35
BIC = 15527.38; SABIC = 15467.02
G2 (236) = 207.6, p = 0.9087
RMSEA = 0, CFI = 1, TLI = 1.073>

Results from linux
> coef(mod1,simplify=TRUE)$cov
     F1   F2 F3
F1 1.00   NA NA
F2 0.25 1.00 NA
F3 0.25 0.25  1

> mod1

Call:
mirt(data = dataset, model = model.1, method = "MHRM")

Full-information item factor analysis with 3 factor(s).
Converged within 0.001 tolerance after 285 MHRM iterations.
mirt version: 1.10.1
M-step optimizer: NR

Log-likelihood = -7736.41, SE = 0.021
AIC = 15510.82; AICc = 15511.2
BIC = 15617.24; SABIC = 15556.87
G2 (236) = 297.28, p = 0.0042

**Comment by philchalmers** [comment]
Is this a syntax related issue? The `COV` statement should be `COV = F1 * F2 * F3`. Though I'm surprised that the behaviour would be different across OSs (it should just crash).

**Comment by philchalmers** [comment]
On my linux box I get orthogonal factors, which is the correct behaviour because factor `F1F2F3` was never defined.

**Comment by katcast** [comment]
Oh, that was a problem with copying/pasting into github. My code was:

model.1 <- mirt.model('
  F1 = 1-3
  F2 = 4-5
  F3 = 6-8
COV = F1*F2*F3')

**Comment by philchalmers** [comment]
You were completely right, this was a recent mistake I made on the dev version (occurred about 3 commits back). Should be fixed now, but let me know if the problem persists. Thanks for the report!

**Comment by katcast** [comment]
Thanks very much!  I tried it again after re-installing mirt from GitHub, and it now works and matches my PC output!  Thanks for the fast fix!
