### ISSUE TITLE
Can I increase MHRM iterations in boot.mirt?

### ISSUE THREAD

**Issue by seonghobae** [philchalmers/mirt#48]
Hello, Phil.

Can I increase MHRM iterations in ```boot.mirt```?
I tried to use technical arguments in ```boot.mirt``` function, but It did not works.

Additionally, I want to know ```group:items``` reflects ```group+items+group:items``` within random argument in ```mixedmirt```. I can not find any description on manual.

```R
entrepreneur.mixed <- mixedmirt(data = trainingset, covdata = person.info, model = entrepreneur.cfa.syntax, random = list(~1+coworker + employees + age + operation_date|industry+items+industry:items), itemtype = 'gpcm', technical = list(NCYCLES = 1e+5))

entrepreneur.mixed.boot <- boot.mirt(entrepreneur.mixed, R = 1000)
MHRM terminated after 2000 iterations.
Error in draw.thetas(theta0 = gtheta0[[g]], pars = pars[[g]], fulldata = Data$fulldata[[g]],  : 
  NAs are not allowed in subscripted assignments
additional information: warnings:
In log(eigen(sigma, symmetric = TRUE, only.values = TRUE)$values) :
  NaN was generated
Error in draw.thetas(theta0 = gtheta0[[g]], pars = pars[[g]], fulldata = Data$fulldata[[g]],  : 
  NAs are not allowed in subscripted assignments
```

**Comment by philchalmers** [comment]
Added the `boot.mirt` option, and no I haven't supported interaction random effects in `mixedmirt()` yet. Currently only crossed random effects are possible. Perhaps one day I'll add that, but not any time soon.

**Comment by philchalmers** [comment]
Oh wait, `mixedmirt()` does already support random interaction effects, but it looks like it does them in isolation (no main effects are included, just the interaction). So your syntax above is fine for the most part, but it looks like it crashes due to instability.

**Comment by philchalmers** [comment]
I see what I did now in the syntax. Each random effect term has to be in an isolated list element instead of in a single equation. So in order to get a random effect for group, item, and group:item you need something like this:

```r
rmod <- mixedmirt(data, covdata, 1, fixed = ~ 0, random = list(~ 1|group, ~ 1|items, ~ 1|group:items))
```

I kept it this way so that random slopes are easier to specify within each level, so conceptually this makes more sense. It also makes it clearer that there are 4 random effects being estimated, so the dimensionality is getting pretty high and there may be difficulty mixing the draws (it's important for each cluster to be relatively large). Hope that helps.

**Comment by seonghobae** [comment]
Okay, I'll check it. Thanks. :+1:
If I put ```group+items+group:items``` in single equation, What will follow to do ```mixedmirt``` function?

**Comment by philchalmers** [comment]
It just defaults to the highest level of generality, so it is equivalent to
~1|group:items. I should probably throw a warning in the future though just
to make this explicit.

**Comment by seonghobae** [comment]
Okay, I hope add that in manual someday. Cheers. :+1:

**Comment by philchalmers** [comment]
Looks like everything here is in order now, so I'll close this issue.
