### ISSUE TITLE
'data inputations'

### ISSUE THREAD

**Issue by seonghobae** [philchalmers/mirt#50]
Hello Phil,

I found a word 'data inputations' in ```M2()```. How about change to 'data imputations' from 'data inputations'?

Best regards,
Seongho Bae

```R
> findM2(mod5, Theta = mod5_theta)
quadpts: 15000 / iteration: 1

 Error: Fit statistics cannot be computed when there are missing data. Pass a suitable
                 impute argument to compute statistics following multiple
                 data inputations 
```

**Comment by philchalmers** [comment]
There's probably typos like this everywhere in the `message()`, `stop()`, and `warning()` functions, and probably some in the documentation. Pull request to fix them? Thanks.
