### ISSUE TITLE
about grsm parametrization

### ISSUE THREAD

**Issue by superpowerkkh** [philchalmers/mirt#57]
Hello,

I am trying grsm model, and I think it should be made clear of the parametrization.

first, for the object from mirt(   , itemtype="grsm")
coef(obj, IRTpars=T) doesn't work.

When I saw the result from coef() and coef( , IRTpars=T) were the same,
I thought the model is parameterized in IRT way.

But as I go trying several times, it found it wasn't. So for anyone I might get confused as I did...

Of course transforming the coefficient is not so hard,
Anyway, do you know any reference about "rating scale graded response model"?

Mostly people say grsm as Generalized Rating Scaling Model which is nested model of GPCM,
I tried searching and googling with no result so far...

**Comment by philchalmers** [comment]
You're right, I should throw a warning for this itemtype (and any other itemtype's that I'm not sure how to transform into the classical metric). Pull requests are welcome for this sort of thing (the function to edit is `mirt2traditional`). 

The GRSM is not a Rasch model, it's actually from the paper: 

Muraki, E. Fitting a polytomous item response model to Likert-type data Applied Psychological Measurement, 1990, 14, 59-71

With the slope-intercept parameterization. I probably should have reference that somewhere in the package (I thought I did, but looking back I guess not).

**Comment by superpowerkkh** [comment]
Thank you for the reference. I wanted to check the parameterization.

And here's what I think...

I think the rating scale model from Muraki(1990) is not the same model as the grsm from mirt.
Muraki's model depends on alpha_i * (theta - ( beta_k + c_i)), (item i, category k)
grsm from mirt depends on alpha_i * theta -( beta_k + c_i ).
So unless the alpha_i's are the same for all items, two models are not the same...

And I don't seem to know how to fit Muraki's model 
unless I can constrain for beta_k/alpha_i to be the same for all items.

I can reparameterize the grsm's parameters into IRT way but 
beta_k would be beta_ik like model "graded"... 

Anyhow oddly grsm fits my data well comparing fit indices from several models...
but I think I have yet to fit Muraki's model to my data

And I tried to find a way to fit Muraki's model in R, 
looking through packages mentioned in 
https://cran.r-project.org/web/views/Psychometrics.html

I found none... Does anyone know how to fit Muraki's model?

**Comment by philchalmers** [comment]
The models are formally equivalent (they will give the same log-likelihood, fit statistics, etc). I just transformed the parameters into slope-intercept form, because honestly that is the proper way to estimate these models. And no I don't think any other R packages estimate this model.

**Comment by superpowerkkh** [comment]
If it's true, I think somehow the same intercepts and the same thresholds made trade-off...
But in case when NAs exist, I don't think they would produce the same result...

Anyhow if it's true, at least for complete data, it's all good for me.. But I need to check it myself...
Could you tell me how you compared both models?

**Comment by philchalmers** [comment]
You don't need to test it, they are mathematically equivalent. For the same reason that when you fit a 2PL model with z = a * (theta - b) or z = a * theta + d, they are interchangeable. Try manipulating Muraki's equation 4 into mirt's slope intercept form. You'll see that they are equivalent.

**Comment by superpowerkkh** [comment]
I hate to say this but I think you got confused...
Models are equivalent but the constraints are not...
In case of 2PL, even if you set all d's are the same, it's not the same as setting b's the same...
Actually I wrote about it in the previous comment.

even though I am very confident about it,
I implemented it with experimental_itemtypes and I got different lokLik.
I also implemented grsm in mirt and I got the almost same lokLik and coefficients as grsm.

So I am pretty sure they are different, I mean the constraints are different 
so the estimates and logLik will be different most of time..

and When I set CONSTRAIN with my experimental itemtypes,
it doesn't seem that BIC and AIC shows the correct values...

and do FIX and START work for experimental item types?

**Comment by philchalmers** [comment]
Care to share your code? I see what you mean with the constraints (same effect would occur when including priors) but I have my doubts that the parametrisations make that much of a difference. I suspect one gives a lower log-likelihood, and if so I'd like to know which. I'm not a fan of the classical approach because as slopes approach 0 the model becomes very unstable, and multidimensional extensions are generally not obvious. 

Also, `mirt` uses the form $z = a1 * theta + d + c$, not the form you mentioned above (I don't include negative terms). Regarding the last two points about constrain, I'll definitely need to see some code to reproduce the issues. It's possible these are little tweaks that haven't been included (after all, experimental itemtype are experimental). Perhaps open up a different issue for each problem and we'll go from there, so we can continue investigating the rating scale differences in this issue. Cheers.

**Comment by superpowerkkh** [comment]
Here's pushed my modified package and code in /tests/tests/test-17_grsm2.R

Here's the code and the result...

I don't know any other way to upload source...

Anyway I thought of implementing myself grsm3 with C or C++ to speed up,
but I think it would be just a bit of tinkering on your side.. :)..

Anyhow for my data, some show higher Likelihood for grsm in mirt,
others show higher Likelihood for grsm3(my implementation).

But mostly grsm3 shows higher Likelihood...

And BIC problem is falsely reported but the second issue remains...
I'll open up another issue..
 
```
# TEST : itemtype = "grsm2", itemtype="grsm3"

R <-
    structure(c(1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 3, 1, 2, 1, 2, 1, 1,
                2, 1, 2, 1, 2, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 2, 2, 1, 2, 2, 1,
                1, 1, 2, 2, 3, 3, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 3, 2, 1, 2, 4,
                1, 2, 2, 2, 1, 1, 4, 1, 1, 2, 1, 1, 3, 2, 1, 4, 1, 2, 2, 2, 2,
                2, 2, 2, 2, 2, 2, 1, 1, 2, 1, 1, 1, 2, 2, 2, 1, 2, 1, 1, 2, 3,
                2, 4, 1, 3, 2, 2, 1, 1, 1, 3, 3, 2, 3, 2, 3, 3, 2, 1, 2, 3, 3,
                3, 1, 1, 1, 3, 3, 2, 2, 3, 1, 3, 3, 1, 2, 2, 3, 1, 3, 2, 2, 3,
                3, 1, 2, 3, 1, 3, 3, 2, 3, 2, 3, 3, 2, 1, 2, 4, 3, 2, 3, 2, 2,
                1, 4, 1, 3, 3, 1, 3, 3, 2, 3, 4, 1, 3, 3, 3, 2, 2, 3, 3, 3, 2,
                2, 3, 1, 2, 1, 1, 1, 2, 2, 3, 3, 3, 1, 3, 2, 3, 2, 1, 4, 2, 2,
                2, 1, 1, 1, 4, 1, 4, 4, 2, 3, 3, 2, 3, 2, 4, 3, 4, 4, 1, 1, 4,
                4, 3, 2, 3, 1, 3, 1, 1, 2, 2, 2, 1, 3, 2, 2, 2, 4, 1, 4, 1, 1,
                4, 3, 1, 3, 3, 4, 3, 2, 1, 2, 4, 3, 4, 4, 2, 1, 1, 4, 1, 3, 3,
                1, 1, 3, 2, 4, 4, 1, 3, 3, 3, 2, 4, 3, 4, 1, 2, 2, 2, 1, 1, 1,
                1, 1, 2, 2, 1, 2, 3, 1, 1, 2, 3, 2, 1, 3, 1, 2, 1, 1, 1, 1, 4,
                1, 4, 1, 2, 3, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 3, 1, 2, 2, 1,
                3, 1, 1, 2, 3, 1, 1, 2, 2, 3, 3, 4, 1, 2, 1, 1, 1, 1, 1, 4, 1,
                3, 3, 2, 1, 2, 1, 3, 4, 3, 1, 3, 1, 4, 1, 3, 1, 1, 1, 3, 2, 1,
                2, 1, 2, 2, 1, 2, 3, 1, 3, 1, 2, 2, 1, 1, 3, 1, 1, 1, 2, 2, 2,
                1, 2, 1, 3, 2, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 4, 4, 1, 4, 2, 2,
                1, 1, 1, 2, 1, 1, 4, 1, 1, 1, 1, 3, 1, 2, 3, 1, 1, 1, 1, 2, 3,
                3, 1, 2, 1, 3, 2, 4, 1, 2, 1, 1, 3, 1, 1, 4, 1, 3, 3, 2, 1, 2,
                1, 3, 4, 1, 1, 1, 1, 2, 1, 1, 3, 1, 1, 3, 2, 1, 1, 1, 4, 4, 2,
                2, 4, 1, 3, 3, 2, 2, 2, 1, 3, 1, 1, 1, 2, 2, 1, 1, 2, 1, 3, 2
    ), .Dim = c(100L, 5L))


ncat = function(R) {
    stopifnot(is.matrix(R))
    max(apply(R, 2, function(x) length(unique(x[!is.na(x)]))))
}

fit.grsm <- mirt(R, 1, itemtype="grsm")

n.item <- ncol(R); ncat <- ncat(R)
model <- paste("F1 = 1-",n.item,
               "\nCONSTRAIN = (1-",n.item,",d1)",
               paste(",(1-",n.item,",d",2:(ncat-1),")",sep="", collapse=""),
               sep="")
pars <- mod2values(fit.grsm);
str(pars[,"class"])
pars[,"class"]=factor(c(rep("grsm2.i1", ncat+1), rep("grsm2", (nrow(pars)-ncat-3)), rep("GroupPars",2)))
#pars[1:(ncat+1),"class"]="grsm2.i1"
#pars[(ncat+2):(nrow(pars)-2),"class"]="grsm2"
fit.grsm2 <- mirt(R, mirt.model(model), pars=pars, itemtype=c("grsm2.i1",rep("grsm2", n.item-1)),
                  TOL=1e-5)

fit.grsm2_ <- mirt(R, mirt.model(model), itemtype=c("grsm2.i1",rep("grsm2", n.item-1)))

pars[,"class"]=factor(c(rep("grsm3.i1", ncat+1), rep("grsm3", (nrow(pars)-ncat-3)), rep("GroupPars",2)))
fit.grsm3 <- mirt(R, mirt.model(model), pars=pars, itemtype=c("grsm3.i1",rep("grsm3", n.item-1)))

coef2mat = function(cf) {
    stopifnot(is.list(cf))
    do.call(rbind, cf[1:(length(cf)-1)])
}


coef2mat(coef(fit.grsm))
coef2mat(coef(fit.grsm2))
coef2mat(coef(fit.grsm2_))
coef2mat(coef(fit.grsm3))

fit.grsm@logLik
fit.grsm2@logLik
fit.grsm2_@logLik
fit.grsm3@logLik



# Do START and FIXED work?

model <- paste("F1 = 1-",n.item,
               "\nCONSTRAIN = (1-",n.item,",d1)",
               paste(",(1-",n.item,",d",2:(ncat-1),")",sep="", collapse=""),
               "\nSTART = (1, c, 0.0)",
               "\nFIXED = (1, c)",
               sep="")

fit.grsm3_ <- mirt(R, mirt.model(model), itemtype=rep("grsm3", n.item))

coef2mat(coef(fit.grsm3))
coef2mat(coef(fit.grsm3_))


```

The Results are

```
> coef2mat(coef(fit.grsm))
       a1     d1     d2     d3      c
par 1.305 -0.068 -2.217 -4.429  0.000
par 1.463 -0.068 -2.217 -4.429  1.594
par 2.557 -0.068 -2.217 -4.429  1.524
par 2.617 -0.068 -2.217 -4.429 -0.015
par 2.816 -0.068 -2.217 -4.429 -0.038
> coef2mat(coef(fit.grsm2))
       a1     d1     d2     d3      c
par 1.305 -0.068 -2.217 -4.429  0.000
par 1.463 -0.068 -2.217 -4.429  1.595
par 2.557 -0.068 -2.217 -4.429  1.525
par 2.617 -0.068 -2.217 -4.429 -0.015
par 2.816 -0.068 -2.217 -4.429 -0.037
> coef2mat(coef(fit.grsm2_))
       a1     d1     d2     d3      c
par 1.305 -0.068 -2.217 -4.428  0.000
par 1.463 -0.068 -2.217 -4.428  1.595
par 2.557 -0.068 -2.217 -4.428  1.525
par 2.616 -0.068 -2.217 -4.428 -0.014
par 2.815 -0.068 -2.217 -4.428 -0.036
> coef2mat(coef(fit.grsm3))
       a1     d1     d2     d3     c
par 3.061 -0.072 -1.188 -2.378 0.000
par 2.749 -0.072 -1.188 -2.378 0.861
par 1.402 -0.072 -1.188 -2.378 0.869
par 1.565 -0.072 -1.188 -2.378 0.104
par 1.249 -0.072 -1.188 -2.378 0.050
> 
> fit.grsm@logLik
[1] -542.1892
> fit.grsm2@logLik
[1] -542.1892
> fit.grsm2_@logLik
[1] -542.1892
> fit.grsm3@logLik
[1] -540.0119
> 
> 
> 
> # Do START and FIXED work?
> 
> model <- paste("F1 = 1-",n.item,
+                "\nCONSTRAIN = (1-",n.item,",d1)",
+                paste(",(1-",n.item,",d",2:(ncat-1),")",sep="", collapse=""),
+                "\nSTART = (1, c, 0.0)",
+                "\nFIXED = (1, c)",
+                sep="")
> 
> fit.grsm3_ <- mirt(R, mirt.model(model), itemtype=rep("grsm3", n.item))
Iteration: 19, Log-Lik: -540.012, Max-Change: 0.00006
> 
> coef2mat(coef(fit.grsm3))
       a1     d1     d2     d3     c
par 3.061 -0.072 -1.188 -2.378 0.000
par 2.749 -0.072 -1.188 -2.378 0.861
par 1.402 -0.072 -1.188 -2.378 0.869
par 1.565 -0.072 -1.188 -2.378 0.104
par 1.249 -0.072 -1.188 -2.378 0.050
> coef2mat(coef(fit.grsm3_))
       a1    d1     d2     d3      c
par 3.066 0.618 -0.496 -1.684 -0.689
par 2.754 0.618 -0.496 -1.684  0.171
par 1.404 0.618 -0.496 -1.684  0.179
par 1.567 0.618 -0.496 -1.684 -0.585
par 1.250 0.618 -0.496 -1.684 -0.639
> fit.grsm3@logLik
[1] -540.0119
> fit.grsm3_@logLik
[1] -540.0119
```

**Comment by superpowerkkh** [comment]
Actually I got a question about implementing...

If I need some speed up, what would be the most efficient way?

1. implementing ProbTrace in C
2. giving analytic gradient and Hessian

**Comment by philchalmers** [comment]
Analytic gradient for sure. The hessian is only needed for the MHRM (and for other special algorithms, the like the S-EM information matrix). Ultimately moving everything into C++ will make the itemtype as fast as the native versions, but supplying just the gradient will get you 90% on the way.

I'm somewhat confused about what I'm looking at above, the parameters look very different. Take a look at the slopes, the 'grsm' model seems to have acceding slopes, while the 'grsm3' seems to have the opposite trend. Maybe it's just an artifact of the sample size. I guess all that really should be compared is the 'grsm' and 'grsm3' itemtypes.

**Comment by superpowerkkh** [comment]
Hi, Thank you for advice. I implemented the analytic derivation at https://github.com/superpowerkkh/mirt_grsm

itemtype: grsmIRT

Since I have my fork for experimenting my models, I had to fork another repo..

The problem is I forked it with help of https://adrianshort.org/create-multiple-forks-of-a-github-repo/
It doesn't seem to be linked to your repo... I can't find my repo from pulling requests...

I searched the internet and I am at a loss with what to do..
If you have any suggestions, I would be very thankful..

And as I implement IRT grsm, I came across overflow/underflow problems...
As I need 1/P and as P(Probability) gets very low, 1/P goes to Inf...

Do you have any possible solutions on your mind?
Currently I switch to numerical Derivation when it happens...

I am thinking of simplifying the expression and using some approximations or
implementing in C using arbitrary precisions(I heard it's possible...)

**Comment by philchalmers** [comment]
On Sun, Nov 1, 2015 at 9:43 AM, superpowerkkh <notifications@github.com>
wrote:

> Hi, Thank you for advice. I implemented the analytic derivation at
> https://github.com/superpowerkkh/mirt_grsm
>
> itemtype: grsmIRT
>
> Since I have my fork for experimenting my models, I had to fork another
> repo..
>
> The problem is I forked it with help of
> https://adrianshort.org/create-multiple-forks-of-a-github-repo/
> It doesn't seem to be linked to your repo... I can't find my repo from
> pulling requests...
>
> I searched the internet and I am at a loss with what to do..
> If you have any suggestions, I would be very thankful..
>

You need to add the master branch to some local branch other than yours,
and either merge or rebase your branch from the master. That will ensure
that the history is correct and that conflicts are dealt with on your end.



> And as I implement IRT grsm, I came across overflow/underflow problems...
> As I need 1/P and as P(Probability) gets very low, 1/P goes to Inf...
>
> Do you have any possible solutions on your mind?
> Currently I switch to numerical Derivation when it happens...
>

For probability tracelines just capping the values to fall between 1e-20
and (1-1e-20) should be sufficient. That seems to be the best way to deter
the optimizer from reaching underflow values.


> I am thinking of simplifying the expression and using some approximations
> or
> implementing in C using arbitrary precisions(I heard it's possible...)
>

Not sure what you mean here, numerical underflow is generally unavoidable
and has to be dealt with carefully.

**Comment by superpowerkkh** [comment]
Sorry actually I dont understand what you are telling.. so I just deleted the previous repo and forked another repo and modified and make a pulling request...

About the underflow problem... I think you misunderstood it.. I was talking about analytic derivations..
If you run the tests.. You'll see "N" being printed while you run the last code.. it means since the analytic derivations can't be computed because of underflow problem.. it changed to numerical derivations...

For analytic derivation I have to compute 1/P_1-1/P_2 and when P gets very small,  1/P_1-1/P_2 becomes NaN, which means I tried to do Inf-Inf... it's because R can't compute or store exp(1000) or larger numbers... so I thought exp-sum-log would be better implementation but it turned out to be of little help... Haven't you come across similar problems? I might post a question about this elsewhere too

**Comment by philchalmers** [comment]
On Wed, Nov 4, 2015 at 8:54 AM, superpowerkkh <notifications@github.com>
wrote:

> Sorry actually I dont understand what you are telling.. so I just deleted
> the previous repo and forked another repo and modified and make a pulling
> request...
>

When in doubt, that always works :)


> About the underflow problem... I think you misunderstood it.. I was
> talking about analytic derivations..
> If you run the tests.. You'll see "N" being printed while you run the last
> code.. it means since the analytic derivations can't be computed because of
> underflow problem.. it changed to numerical derivations...
>
> For analytic derivation I have to compute 1/P_1-1/P_2 and when P gets very
> small, 1/P_1-1/P_2 becomes NaN, which means I tried to do Inf-Inf... it's
> because R can't compute or store exp(1000) or larger numbers... so I
> thought exp-sum-log would be better implementation but it turned out to be
> of little help... Haven't you come across similar problems? I might post a
> question about this elsewhere too
>

Yes I've noticed this before, especially when the parameters are extreme.
Usually just capping them as well where appropriate will help (e.g.,
https://github.com/philchalmers/mirt/blob/master/src/dpars.cpp, line 871).
If the derivatives require division by some small number then setting the
term to 1e-10 seems to work fairly well.
