### ISSUE TITLE
double key is unavailable in 2PLNRM

### ISSUE THREAD

**Issue by seonghobae** [philchalmers/mirt#60]
Hi, Phil.

Double key is unavailable in 2PLNRM.

```R
> key <- cbind(c(4,4,1,2,2,1,3,4,1,2),
+                c(rep(NA,4),1,rep(NA,4),3))
> mod4 <- mirt(Data[12:21], 2, itemtype = '2PLNRM', key = key, optimizer = 'nlminb', technical = list(removeEmptyRows=TRUE))
Error: The number of elements in the key input is incorrect.
```

**Comment by philchalmers** [comment]
I think this is the right behavior. Double keys aren't really clear with the nested logit models, and modifying the data internally runs the risk of causing confusion. 

A workaround solution is to transform your data such that only one key is required. So if, for item 1, responses 3 and 5 should be considered 'correct' you should transform all 5's to 3's and only supply a key of 3 for that item.

**Comment by philchalmers** [comment]
Was this a satisfactory response? If so, please close the issue.
