### ISSUE TITLE
residuals in block design

### ISSUE THREAD

**Issue by akaat** [philchalmers/mirt#62]
I first raised this problem on the google groups. Can I get LD values in a block-design study? Attached is a tab-delimited data file and very brief R code recreating this error. 

[sim20_Rcode.txt](https://github.com/philchalmers/mirt/files/37209/sim20_Rcode.txt)
[sim20dat.txt](https://github.com/philchalmers/mirt/files/37204/sim20dat.txt)

**Comment by philchalmers** [comment]
Thanks Aaron, this was very helpful in tracking down the issue. The current fix now is to just put NaN elements in situations where the tables can't be formed, which is pretty systematic for block designs. Let me know if you see any other related problems to sparse data. Cheers.
