### ISSUE TITLE
EAPsum scores for multiple group model

### ISSUE THREAD

**Issue by dorock2** [philchalmers/mirt#64]
Hi all:  Although I have not run across a formal definition for EAPsum scores in multiplegroup MIRT, I thought they were estimated scale scores, i.e, sums of the probabilties across items for each individual..  If that is not what they are then my following question does not apply.  I am not sure why I am getting and error message to the tune of "cannot estimate EAPsum scores with missing data.  If indeed they are sums of the probabilities missing data do not matter.  Thanks for any help on this matter.  Don Rock

**Comment by philchalmers** [comment]
They aren't that, they are EAP scores that have been conditioned on the raw sum score. Which is why you can't get them when missing data are present. You can get EAP scores though just fine, as the standard errors will account for the missing item response data.
