### ISSUE TITLE
[Forward from Google group] Mstep Optimization problem when try to contain polynomial terms

### ISSUE THREAD

**Issue by seonghobae** [philchalmers/mirt#71]
[fixMstepOptimPolynomial.zip](https://github.com/philchalmers/mirt/files/76718/fixMstepOptimPolynomial.zip)

See details: https://groups.google.com/forum/#!topic/mirt-package/PkhO_GDTHps

Seongho

**Comment by philchalmers** [comment]
I'm having trouble grasping how to model latent polynomial constructed terms with latent regression effects, likely indicating that it's not reasonable to do (polynomial terms don't have unique variance, so their variance decomposition seems unreasonable). An error is thrown now instead, and was also the issue with #72.
