### ISSUE TITLE
Error running fscores with response.pattern option

### ISSUE THREAD

**Issue by manieldack** [philchalmers/mirt#78]
Hey Phil,

I wanted to let you know of a small issue my colleague and I found when updating to your latest code (both the 1.16 and from the Git). It appears that when we try to run fscores with a previously made model and new data in response.pattern we get this error:

Error in `*tmp*`[[i]] : attempt to select less than one element

We tracked it down to an issue of not including the K parameter in the newmod objects data attribute. We were able to fix this by changing the line in fscores_internal.R:

newmod@Data <- list(data=response.pattern, tabdata=large$tabdata2,
                                   tabdatalong=large$tabdata, Freq=large$Freq)

to 

newmod@Data <- list(data=response.pattern, tabdata=large$tabdata2,
                                   tabdatalong=large$tabdata, Freq=large$Freq, K = object@Data$K)

I know this may not be how you want to pass the K atttribute into the object, but we made this change and verified that it did work with a saved model and new data (which was just the original data used to train the model) to compare to known results. 

Due to outside issues we are unable to follow the by the book method of contributing to the Git and help you improve this, thus the long rambling issue request. We really enjoy using this package quite a bit, and I want to thank you for putting in the time to make it relatively easy to work with (considering the topic). Please let me know if you need me to help flesh out any more context around this issue.

Thanks,
Dan

**Comment by philchalmers** [comment]
Thanks Dan. I've made the patch that you've recommended. Could you try out the latest version to see if it's fixed on your end, and if so could you close the issue? Cheers.

**Comment by manieldack** [comment]
Looks good. Thanks again!
