### ISSUE TITLE
Citation error

### ISSUE THREAD

**Issue by awmeade** [philchalmers/mirt#79]
Minor error in the Drasgow, Levine, & Williams (1985) citation.  Journal should be British Journal of.... the British part is missing.

**Comment by philchalmers** [comment]
Too bad, "Journal of Mathematical and Statistical Psychology" sounded way cooler. Thanks

**Comment by awmeade** [comment]
:)

By the way, I just left the big I/O psychology conference and mentioned to
my IRT using friends that mirt is a great package for invariance tests.

Quick question, to assess item model fit, you would recommend the S-X2?

Adam

Adam

**Comment by philchalmers** [comment]
I would. It seems to work pretty well with decent Type I error control. Not overly powerful though, but functional nonetheless.

**Comment by awmeade** [comment]
Great.  thanks.  --adam

Adam
