### ISSUE TITLE
GRM example broken

### ISSUE THREAD

**Issue by ryentes** [philchalmers/mirt#81]
The mirt GRM example on [this](http://philchalmers.github.io/mirt/html/ltm_models_with_mirt.html) page just shows me an error instead of the actual output.

**Comment by philchalmers** [comment]
It's because ltm is masking the science dataset that ships with mirt. Load mirt first and assign it to a different object, like dat <-   Science

**Comment by ryentes** [comment]
Yeah, "Broken" was probably a bit dramatic. That allowed me to run it locally. Thanks!
