### ISSUE TITLE
Bayes Factor

### ISSUE THREAD

**Issue by Barbetta** [philchalmers/mirt#88]
Dear Phil Chalmers,
My doubt is about the Bayes Factor in mirt.anova. This is always in the interval [0, 1], because the difference of the log-posterior is always  < 0, when I write anova (m1,m2) or anova(m2,m1) the result is the same. Is it correct? I would expect the Bayes Factor  > 1.
Best regards,
Pedro

**Comment by philchalmers** [comment]
This is the wrong place for Q&As, the forum would be better.
