### ISSUE TITLE
ideal-point model with mixedmirt isn't working

### ISSUE THREAD

**Issue by seonghobae** [philchalmers/mirt#93]
Hello, Phil.

I have a trouble to run the ideal-point model with mixedmirt function. But It's not working.

That's available to run?

Seongho

```R
> mixedmirt(modOverallDataset, model = 1, itemtype = 'ideal')
Error in draw.thetas(theta0 = gtheta0[[g]], pars = pars[[g]], fulldata = Data$fulldata[[g]],  : 
  MH sampler failed. Model is likely unstable or may need better starting valuesFALSE
> mixedmirt(modOverallDataset, model = 1, itemtype = 'ideal', GenRandomPars = T)
Error in draw.thetas(theta0 = gtheta0[[g]], pars = pars[[g]], fulldata = Data$fulldata[[g]],  : 
  MH sampler failed. Model is likely unstable or may need better starting valuesFALSE
```

**Comment by philchalmers** [comment]
Does an error occur when a `covdata` argument is supplied? When passing this to `mirt()` it looks like it runs fine (there's no need for mixedmirt here because there are no covariates).

**Comment by philchalmers** [comment]
I see the problem, spline and ideal itemtypes can't add an intercept to the formulation easily. A default warning is now thrown and auto-fixed (`fixed = ~ -1` by default for these models to disable the intercept decompositions and remove the default 1's).

**Comment by seonghobae** [comment]
Okay, I check out it. and One more step;

When I try to calibrate ideal point model with the mixedmirt in current dev version, fixed effect term has ignored to calibrated model.

```R
> summary(mixedmirt(modOverallDataset_ideal, 1, covdata = Data[59:73], itemtype = 'ideal', SE = T, fixed = ~-1 + items + age + teamyear + sex + edu + Role + bizcode.1 + jobarea + position + totalmem, random = list(~1|teamid)))
Warning: Unsupported itemtype detected for modeling intercepts.
fixed = ~ -1 used by default to remove intercept
Stage 3 = 11, LL = -12614.3, AR(0.50; 4.77) = [0.20; 0.03], gam = 0.0316, Max-Change = 0.0009

Calculating information matrix...

Calculating log-likelihood...

Call:
mixedmirt(data = modOverallDataset_ideal, covdata = Data[59:73], 
    model = 1, fixed = ~-1 + items + age + teamyear + sex + edu + 
        Role + bizcode.1 + jobarea + position + totalmem, random = list(~1 | 
        teamid), itemtype = "ideal", SE = T)


--------------
RANDOM EFFECT COVARIANCE(S):
Correlations on upper diagonal

$Theta
   F1
F1  1

$teamid
           COV_teamid
COV_teamid      0.031

```

**Comment by philchalmers** [comment]
Correct, the fixed input is now just ignored for these itemtypes because there is no easy intercept decomposition. The random term also should have been disabled, which it now is as well. Only the lr.fixed and lr.random inputs work for these models to decompose the latent trait effects.

**Comment by seonghobae** [comment]
Okay, I got it. Hence, If I try to work only the lr.fixed and lr.random inputs, that constrain latent trait level variances?; not item level probability?

**Comment by philchalmers** [comment]
Correct. Item level probability is modified more globally based on the
theta values and their regression effects. So, generally not as fine tuned
(as I mentored in the paper).
