### ISSUE TITLE
EAPsum() - Error in t(t(dat) - adj): dims do not match the length of object [0]

### ISSUE THREAD

**Issue by Evadeschipper** [philchalmers/mirt#94]
Hi Phil,

When trying to apply the fscores function using the EAPsum method, like this (using a brief reproducable example): 

    data <- matrix(sample(1:5, 250, replace=T), nrow=25, ncol=10)
    grm <- mirt(data,model=1,itemtype="graded", technical=list(removeEmptyRows=TRUE))
    thetas.EAP <- fscores(grm,method="EAPsum",response.pattern=data,full.scores=T,full.scores.SE=T,theta_lim=c(-4,4))

I run into the following error: 

    Error in t(t(dat) - adj) : 
      dims [product 250] do not match the length of object [0]

I found the source of the error to be the following lines from the internal EAPsum function (https://github.com/philchalmers/mirt/blob/master/R/fscores.internal.R). 

    dat <- x@Data$data
    adj <- x@Data$min
    dat <- t(t(dat) - adj)

When applying this manually to the model (`grm`), I notice that `grm@Data$min` is not a valid option, but `grm1@Data$mins` (with an s behind it) is. When I manually calculate `dat` like this, using `mins` instead of `min`, there is no problem. 

Thanks in advance,
Eva

**Comment by philchalmers** [comment]
Thanks for the report, very helpful. Should be patched now, and it appeared that the 'EAPsum' option wasn't as consistent with the rest of the package format (supplying a `response.pattern` input shouldn't require the `full.scores` inputs, and should return SEs by default). This was also updated. HTH, and thanks again.

**Comment by Evadeschipper** [comment]
Great! Thanks for the quick reply and patch.

**Comment by philchalmers** [comment]
FYI, here's what I used to test the bahaviour:

```r
set.seed(1)
data <- as.data.frame(matrix(sample(1:5, 250, replace=T), nrow=25, ncol=5))
grm <- mirt(data,model=1,itemtype="graded", technical=list(removeEmptyRows=TRUE))

fscores(grm,method="EAPsum", full.scores.SE=TRUE)
fscores(grm,method="EAPsum",response.pattern=data, theta_lim=c(-4,4))
fscores(grm,method="EAPsum",response.pattern=data[1,], theta_lim=c(-4,4))
```
