### ISSUE TITLE
mirt package problem

### ISSUE THREAD

**Issue by mddavila** [philchalmers/mirt#97]
Hi Phil Chalmers, 

I have recently update my mirt 1.19 package to it's new 1.21 version in my macbook pro 2013 with macOS Sierra version 10.12.2 (Xcode Command Line Tools 8.2) . However when I plot a confirmatory MIRT model, which seems to works in previous versions, the plot show a strange message - "Error using packet 1 negative length vectors are not allowed" (see picture below). 

![mirt version 1 21](https://cloud.githubusercontent.com/assets/17376295/21261806/705d575e-c36c-11e6-9021-2693208b4f21.png)
![mirt previous packages](https://cloud.githubusercontent.com/assets/17376295/21261844/a42c03f0-c36c-11e6-840e-18088186d2c2.JPG)

my code: 
IRT <- mirt.model('T = 1,3,4,5,7,8,9,10,12,15,16
              ST = 2,6,11,13,14
                  COV = T*ST,4*5,7*8,13*14')
(IRTmodel3 <- mirt(data, IRT))
summary(IRTmodel3)
plot(IRTmodel3)

While I check the possible causes of this situation I found a strange warning in the package's compilation: 

> library('devtools')
> install_github('philchalmers/mirt')
Downloading GitHub repo philchalmers/mirt@master
from URL https://api.github.com/repos/philchalmers/mirt/zipball/master
Installing mirt
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/1l/xcx88qj10w96r83qn2_4xjfc0000gn/T/RtmpR1ZDGX/devtools5ea4ba7cf5b/philchalmers-mirt-5e3f006'  \
  --library='/Library/Frameworks/R.framework/Versions/3.3/Resources/library'  \
  --install-tests 

* installing *source* package ‘mirt’ ...
** libs
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.3/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.3/Resources/library/RcppArmadillo/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c Estep.cpp -o Estep.o
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.3/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.3/Resources/library/RcppArmadillo/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c Misc.cpp -o Misc.o
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.3/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.3/Resources/library/RcppArmadillo/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c dpars.cpp -o dpars.o
**dpars.cpp:1502:15: warning: unused variable 'npfact' [-Wunused-variable]
    const int npfact = Theta.ncol() - nsfact;
              ^
1 warning generated.**
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.3/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.3/Resources/library/RcppArmadillo/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c traceLinePts.cpp -o traceLinePts.o
clang++ -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o mirt.so Estep.o Misc.o dpars.o traceLinePts.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/lib/gcc/x86_64-apple-darwin13.0.0/4.8.2 -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/3.3/Resources/library/mirt/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** tests
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (mirt)

I have checked the internet however due to my lack in expertise I could not find and answer. Could you give me any help? I will really thank you a lot. 

NOTE: This strange warning message remains even when I install the new version through CRAN or git.

**Comment by philchalmers** [comment]
The warning messages don't look fatal, they just indicate that some variables were defined but not used. The problem seems to be in the COV definition; why are there numbers in the right hand definition? They should just be factor names.

**Comment by mddavila** [comment]
My mistake, when I copied the code here the stars got erased. This is the right code I used to plot the images you have seen before with the different mirt package versions: 

IRT <- mirt.model('T = 1,3,4,5,7,8,9,10,12,15,16
ST = 2,6,11,13,14
COV = T*ST,4*5,7*8,13*14')
(IRTmodel3 <- mirt(data, IRT))
summary(IRTmodel3)
plot(IRTmodel3)

I wrote the  "4*5, 7*8, 13*14" in order to define the error covariance between some items  of my model. Due to your advice, I tried the same model without this numbers, however, the same strange plot keeps appearing: 

![mirt previous packages](https://cloud.githubusercontent.com/assets/17376295/21275480/cdda0316-c3ab-11e6-96cb-a98b1707a125.JPG)

An additional observation is that when I print the model's fit (with or without the error covariance numbers), it does not give me the common fit indices (RMSEA, CFI, TLI, etc.) as in the mirt's wiki example:

> IRT <- mirt.model('T = 1,3,4,5,7,8,9,10,12,15,16
+               ST = 2,6,11,13,14
+                   COV = T*ST')
> IRTmodel3 <- mirt(data, IRT)
Iteration: 33, Log-Lik: -3063.031, Max-Change: 0.00010
> print(IRTmodel3)

Call:
mirt(data = data, model = IRT)

Full-information item factor analysis with 2 factor(s).
Converged within 1e-04 tolerance after 33 EM iterations.
mirt version: 1.21 
M-step optimizer: BFGS 
EM acceleration: Ramsay
Number of rectangular quadrature: 31

Log-likelihood = -3063.031
Estimated parameters: 95 
AIC = 6316.061; AICc = 6688.306
BIC = 6598.851; SABIC = 6298.237
> 

Although when I try the "M2" function it does give me this indices:

> M2(IRTmodel3)
            M2 df            p      RMSEA    RMSEA_5  RMSEA_95      SRMSR
stats 87.07055 41 3.652965e-05 0.08833616 0.06222941 0.1137117 0.07067132
            TLI       CFI
stats 0.8145342 0.8688948

Thank you very much for your help and fast response!

NOTE: sorry for my bad english, I'm a native spanish speaker.

**Comment by philchalmers** [comment]
That's not what I meant. I mean `COV = T*ST,4*5,7*8,13*14')` is not valid syntax because it shouldn't contain number terms. This is because for categorical item there is *no* residual co-variation (this only occurs for continuous distributions). So that's why this doesn't run. 

If you want residual factors, you need to specify them explicitly, and identify the model correctly as well by constraining their respective slopes to be equal. The bifactor/two-tier model is really what you are looking for, so see the ?bfactor function. 

The second part about why the default CFI is not printed is related to data sparceness, so it wouldn't be valid to compute anyway. For M2, this sparceness is less of an issue.

**Comment by mddavila** [comment]
If that is the case, why I can't get the same plot with the same code in the different mirt package versions?

IRT <- mirt.model('T = 1,3,4,5,7,8,9,10,12,15,16
ST = 2,6,11,13,14
COV = T*ST')
IRTmodel3 <- mirt(data, IRT)

thank you!

**Comment by philchalmers** [comment]
The above code should be fine regardless of the version you use. Of course, under-the-hood things do change (for the better), so the latest version is likely the one that is correct.
